import { CONFIG } from './content.shared';

export const CONTENT_ZH = {
	meta: {
		title: 'TAICHI 2026 | Big Bang! Futures!',
		description: '第 12 屆台灣人機互動研討會。主題：Big Bang! Futures!',
		url: 'https://taichi2026.taiwanchi.org',
	},
	nav: {
		logo: 'TAICHI 2026',
		home: 'HOME',
		news: 'NEWS',
		theme: 'THEME',
		program: 'AGENDA',
		keynotes: 'KEYNOTES',
		organization: 'ORGANIZATION',
		cfp: 'CALL FOR PAPERS',
		familyFriendly: 'FAMILY-FRIENDLY',
		venue: 'VENUE',
		registration: 'REGISTRATION',
		notion: 'DB ADMIN',
		notionUrl: 'https://www.notion.so/',
		cfpSubmenu: [
			{ label: 'Important Date', hash: '#important-dates' },
			{ label: 'Themes', hash: '#themes' },
			{ label: 'Paper & Pictorial', hash: '#papers' },
			{ label: 'Poster', hash: '#posters' },
			{ label: 'Demo', hash: '#demos' },
		],
	},
	heroBanner: {
		topText: ' ',
		bottomText: ' ',
	},
	submissionDeadline: {
		title: '投稿截止日期',
		date: '2026/6/18（四）23:59 (GMT+8)',
		buttonText: '立即投稿',
	},
	theme: {
		title: 'TAICHI2026：Big Bang! Futures!',
		slogan: '未來將不再以低語傳遞，而是以爆炸式發生。',
		description:
			'第12屆台灣人機互動研討會主題「Big Bang! Futures」源自宇宙霹靂般的起始瞬間，象徵想法快速擴散、改變世界的一刻。我們將這個瞬間帶進城市，化為一個可以逛、可以玩、可以一起參與的未來現場，透過互動裝置、實驗作品與夜市般的體驗空間，邀請民眾親身感受並討論科技如何影響未來生活與彼此之間的關係，讓多重未來在連鎖爆發中持續 Big Bang！',
	},
	cfpSection: {
		title: 'Call For Papers',
		subtitle: '投稿資訊',
		topicsTitle: '研討會主題',
		importantDatesTitle: '重要時程',
		submissionLink: 'https://easychair.org/conferences/?conf=taichi2026',
		heroDeadlineNote: '截投稿截止日期: 2026/06/18 23:59 (GMT+8)',
		heroTimelineItems: [
			{ title: 'DEADLINE', date: '06.18', subtitle: '投稿截止日期' },
			{ title: 'NOTIFICATION', date: '07.21', subtitle: '審查結果通知' },
			{ title: 'CAMERA-READY DEADLINE', date: '07.27', subtitle: '最終完稿截止日期' },
			{ title: 'CONFERENCE', date: '08.05-06', subtitle: '會議日期' },
		],
		exploreMore: 'EXPLORE MORE',
		topics: [
			{ en: 'Usability and User Experience', ch: '可用性與使用者體驗' },
			{ en: 'Interaction Techniques and Devices', ch: '互動技術與裝置' },
			{ en: 'Understanding Users and Human Behavior', ch: '理解使用者與人類行為' },
			{ en: 'Design Methods and Processes', ch: '設計方法與流程' },
			{ en: 'Mobile and Ubiquitous Computing', ch: '移動與普適計算' },
			{ en: 'Virtual, Augmented, Mixed, and Extended Reality (VR, AR, MR, XR)', ch: '虛擬、擴增、混合與擴展實境' },
			{ en: 'Human-AI Interaction', ch: '人工智慧與人類互動' },
			{ en: 'Social Computing and Collaboration', ch: '社群運算與協作' },
			{ en: 'Ethics, Accessibility, and Inclusive Design', ch: '倫理、無障礙與包容性設計' },
			{ en: 'More-than-Human Design', ch: '超越人本中心的設計' },
			{ en: 'Specific Application Areas', ch: '特定應用領域 (如學習、健康、家居、設計輔具等)' },
		],
		categories: [
			{
				id: 'papers',
				title: '論 文 與 圖 像 式 論 文',
				date: '2026/6/18(四) 23:59 (GMT+8)',
				notification: '2026/7/21(二) 23:59 (GMT+8)',
				cameraReady: '2026/7/27(一) 23:59 (GMT+8)',
				links: [
					{ label: 'Latex Template', url: 'https://portalparts.acm.org/hippo/latex_templates/acmart-primary.zip' },
					{ label: 'Overleaf Template', url: 'https://www.overleaf.com/latex/templates/acm-conference-proceedings-primary-article-template/wbvnghjbzwpc' },
					{ label: 'Microsoft Word for Windows', url: 'https://www.acm.org/binaries/content/assets/publications/word_style/interim-template-style/interim-layout.docx' },
					{ label: 'Macintosh Office 2011', url: 'https://portalparts.acm.org/hippo/enhanced_word_templates/MAC_2011/mac_2011.zip' },
					{ label: 'Macintosh Office 2016', url: 'https://portalparts.acm.org/hippo/enhanced_word_templates/MAC_2016/mac_2016.zip' },
					{ label: 'Pictorials InDesign Template', url: 'https://dis.acm.org/2025/wp-content/uploads/2024/11/DIS2021-Pictorials-InDesign-template_Folder.zip' },
					{ label: 'Pictorials Word Template', url: 'https://dis.acm.org/2025/wp-content/uploads/2024/11/DIS2021-Pictorials-Word-template-Folder.zip' },
					{ label: 'Pictorials Powerpoint Template', url: 'https://dis.acm.org/2025/wp-content/uploads/2024/11/DIS2021-Pictorials-PowerPoint-template-Folder.zip' },
				],
				description: [
					'論文為呈現完整且尚未公開發表之新研究成果的主要媒介；通過審查的論文將被排入研討會發表議程。中英文論文投稿均可，所有投稿需依循 ACM SIGCHI 之雙欄撰寫 paper 格式或採用 DIS 的 pictorial 格式。',
					'論文（Full Paper）',
					'Full Paper 論文投稿格式範本請至 ACM CHI/UIST/DIS 官方網站下載 Sumbission Formats (paper格式)，請作者依照個人偏好的編輯軟體，從下列的連結下載對應的範本檔案：',
					'● [Latex Template](https://portalparts.acm.org/hippo/latex_templates/acmart-primary.zip)',
					'● [Overleaf Template](https://www.overleaf.com/latex/templates/acm-conference-proceedings-primary-article-template/wbvnghjbzwpc)',
					'● [Microsoft Word for Windows](https://www.acm.org/binaries/content/assets/publications/word_style/interim-template-style/interim-layout.docx)',
					'其他資訊請參考 [ACM Template](https://www.acm.org/publications/proceedings-template) 網頁說明。TAICHI 論文頁數**以 8~12 頁為原則但不超過 12 頁**（不含參考文獻），，中文版本字體請使用標楷體，字級則與英文論文相同，均須依循ACM SIGCHI格式規範，請參考範本文件中的內容說明。',
					'圖像式論文（Pictorial）',
					'Pictorial 設計論文格式請參考 [ACM DIS2025](https://dis.acm.org/2025/call-for-pictorials/) 的說明來進行準備 。以下提供範本檔案的連結，請作者依照個人偏好的軟體，下載相對應的檔案來編輯投稿文件：',
					'● [Pictorials InDesign Template](https://dis.acm.org/2025/wp-content/uploads/2024/11/DIS2021-Pictorials-InDesign-template_Folder.zip)',
					'● [Pictorials Word Template](https://dis.acm.org/2025/wp-content/uploads/2024/11/DIS2021-Pictorials-Word-template-Folder.zip)',
					'● [Pictorials Powerpoint Template](https://dis.acm.org/2025/wp-content/uploads/2024/11/DIS2021-Pictorials-PowerPoint-template-Folder.zip)',
					'TAICHI Pictorial 論文頁數**以 8~12 頁為原則但不超過 12 頁**（不含參考文獻）。首頁請按照統一格式排版，若為中文版本字體請使用標楷體，字級則與英文論文相同，均須依循ACM SIGCHI格式規範，請參考範本文件中的內容說明。其他頁則自由排版。',
					'備註',
					'● 所有投稿論文皆採**雙向匿名 (Double-blind)** 審查，請上傳匿名 PDF 檔；若未匿名將直接退稿。PDF 含附件須**小於 20MB**，，請作者用 Acrobat 的最佳化功能，縮減檔案的大小同時確保內容可以清楚地呈現在螢幕上。',
					'● 被錄取論文將收錄於非正式的TAICHI 2026 線上論文集，放置雲端供大家下載閱讀；作者若有投稿疑慮，亦可選擇以摘要形式收錄於非正式的TAICHI 2026線上論文集。',
					'直接退稿規定',
					'● 若投稿論文之主題與研討會徵稿範圍不符、研究貢獻不明確或未完整呈現，或未依規定格式撰寫，主辦單位有權於審查前進行初步篩選並直接退稿（desk reject）。以下為可能之情況說明：',
					'● ● __研究範疇（Scope）__：未能充分回顧相關文獻，或缺乏足夠脈絡以說明研究之新穎性與對設計研究或互動系統領域之貢獻。論文應適當建立於既有研究、設計實務或相關領域之基礎上，且其貢獻應與篇幅相符。',
					'● ● __方法論（Methodology）__：未提供足夠資訊以說明研究方法與過程，包含概念架構不清、論證不完整，或缺乏方法描述與研究透明度。',
					'● ● __資料（Data）__：缺乏足夠資料或證據支持分析與研究主張，致使研究結論難以驗證。',
					'論文主席',
					'Yaliang Chuang / 莊雅量 / 國立清華大學藝術與設計系',
					'Shan Yuan Teng / 鄧善元 / 國立臺灣大學資訊工程學系',
					'Hsin-Ruey (Ray) Tsai / 蔡欣叡 / 國立政治大學資訊科學系',
					'Yu-Chun (Grace) Yen / 顏羽君 / 國立陽明交通大學資訊工程系',
					'論文投稿相關問題請洽 [taiwanchi26+paper@gmail.com](mailto:taiwanchi26+paper@gmail.com)',
				],
			},
			{
				id: 'posters',
				title: '海 報 論 文',
				date: '2026/6/18(四) 23:59 (GMT+8)',
				notificationDate: '2026/7/21(二) 23:59 (GMT+8)',
				cameraReadyDate: '2026/7/27(一) 23:59 (GMT+8)',
				links: [
					{ label: 'Latex', url: 'https://portalparts.acm.org/hippo/latex_templates/acmart-primary.zip' },
					{ label: 'Overleaf', url: 'https://www.overleaf.com/latex/templates/acm-conference-proceedings-primary-article-template/wbvnghjbzwpc' },
					{ label: 'Word', url: 'https://uist.acm.org/2023/assets/files/word-two-column-submission-sample.docx' },
				],
				description: [
					'海報提供作者與研討會參與者直接互動討論正在進行或已在其他研討會發表的研究。受錄取的海報將在研討會海報時段呈現，並且需要至少有一位作者參加研討會並在指定的海報時段進行海報展示。',
					'投稿格式',
					'● 投稿需依循 ACM SIGCHI Publication Format (雙欄) 撰寫，檔案必須為 PDF 檔。',
					'● 投稿格式範本如下：[Latex](https://portalparts.acm.org/hippo/latex_templates/acmart-primary.zip), [Overleaf](https://www.overleaf.com/latex/templates/acm-conference-proceedings-primary-article-template/wbvnghjbzwpc), [Word](https://uist.acm.org/2023/assets/files/word-two-column-submission-sample.docx)',
					'● TAICHI 海報論文頁數**以四頁為原則**（不含參考文獻）。',
					'● 論文內容必須包含摘要、研究動機、目的、方法、目前成果、以及未來研究規劃。',
					'● 海報稿件只需上傳論文，海報檔案將於確定被接受後上傳。',
					'● 所有海報將列入海報論文獎審查，得獎者由會議參與者匿名投票選出。',
					'備註',
					'● 海報投稿採非匿名審查，請在論文中呈現所有必須之作者資訊。請上傳無匿名的 PDF 檔案，如果沒有附上作者資訊，將直接退稿。',
					'● 論文 PDF 檔案含附件須小於 20MB，請作者用 Acrobat 的最佳化功能，縮減檔案的大小同時確保內容可以清楚地呈現在螢幕上。',
					'● 被錄取論文將收錄於非正式的TAICHI 2026 線上論文集，放置雲端供大家下載閱讀；作者若有投稿疑慮，亦可選擇以摘要形式收錄於非正式的TAICHI 2026線上論文集。',
					'● 若投稿論文之主題與研討會徵稿範圍不符、研究貢獻不明確或未完整呈現，或未依規定格式撰寫，主辦單位有權於審查前進行初步篩選並直接退稿（desk reject）。參照Full Paper 與 Pictorial論文規定。',
					'● TAICHI 2026 將與其他國際活動聯合舉辦，鼓勵海報用英文呈現。',
					'海報主席',
					'Chiu-Hsuan Wang / 王秋玄 / 臺大資訊管理系博士後研究員',
					'Fu-Yin Cherng / 程芙茵 / 成大資訊工程系助理教授',
					'Wei-Ming Chung / 莊偉銘 / 銘傳大學商品設計系講師',
					'● 海報論文投稿相關問題請洽 [taiwanchi26+poster@gmail.com](mailto:taiwanchi26+poster@gmail.com)',
				],
			},
			{
				id: 'demos',
				title: '互 動 展 示',
				date: '2026/6/18(四) 23:59 (GMT+8)',
				notificationDate: '2026/7/21(二) 23:59 (GMT+8)',
				cameraReadyDate: '2026/7/27(一) 23:59 (GMT+8)',
				links: [
					{ label: 'Latex', url: 'https://portalparts.acm.org/hippo/latex_templates/acmart-primary.zip' },
					{ label: 'Overleaf', url: 'https://www.overleaf.com/latex/templates/acm-conference-proceedings-primary-article-template/wbvnghjbzwpc' },
					{ label: 'Word', url: 'https://uist.acm.org/2023/assets/files/word-two-column-submission-sample.docx' },
					{ label: '場地需求申請表', url: 'https://docs.google.com/document/d/1uMsKeIa64dYQAFFQLggcIR7leRA1TC7Jc2RsYja3YTY' },
				],
				description: [
					'展示直接於研討會上展現互動概念、手法、裝置或系統的實作成果。受錄取的展示可在展示時段於研討會場中擺設攤位呈現。',
					'投稿格式',
					'● 投稿需依循 ACM SIGCHI Extended Abstract 之格式撰寫。檔案必須為 PDF 檔，不需匿名。標準格式請至 ACM SIGCHI 官方網站下載 CHI Publication Formats。',
					'● 投稿格式範本如下：[Latex](https://portalparts.acm.org/hippo/latex_templates/acmart-primary.zip), [Overleaf](https://www.overleaf.com/latex/templates/acm-conference-proceedings-primary-article-template/wbvnghjbzwpc), [Word](https://uist.acm.org/2023/assets/files/word-two-column-submission-sample.docx)',
					'● 稿件總頁數**上限為三頁**（不含參考文獻），格式採**雙欄排版**。內容可使用中英文撰寫，中文部分請使用標楷體字型。',
					'● 內容必須包含摘要、研究動機、目的、方法、目前成果、以及未來研究規劃。',
					'● 論文標題需以「 Demo: 」為開頭。若同時為 Poster，標題請以「 Poster & Demo: 」為開頭。',
					'● 鼓勵上傳影片以便衡量系統的互動性以及完整程度。上傳影片前請先以 HandBrake 進行壓縮，並輸出成 H.264 之.mp4 檔案。',
					'● 需繳交一份「[場地需求申請表](https://docs.google.com/document/d/1uMsKeIa64dYQAFFQLggcIR7leRA1TC7Jc2RsYja3YTY)」，展示主席將依此協助當天的布展安排。',
					'● 所有系統展示將列入系統展示論文獎審查，得獎者由會議參與者匿名投票選出。',
					'備註',
					'● 被錄取論文將收錄於非正式的TAICHI 2026 線上論文集，放置雲端供大家下載閱讀；作者若有投稿疑慮，亦可選擇以摘要形式收錄於非正式的TAICHI 2026線上論文集。',
					'● 屆時請於會議展示時段前完成攤位佈置。',
					'● TAICHI 2026 將會跟其他國際活動聯合舉辦，鼓勵大家海報用英文呈現。',
					'展示主席',
					'Ching-Wen Hung / 洪靖雯 / 臺大資訊網路與多媒體研究所博士候選人',
					'● 展示投稿相關問題請洽 [taiwanchi26+demo@gmail.com](mailto:taiwanchi26+demo@gmail.com)',
				],
			},
		],
	},
	newsSection: {
		title: 'NEWS',
		subtitle: '最新消息',
		loadMore: '載入更多',
		showLess: '收合',
		readMore: '閱讀更多',
		viewAll: '查看全部消息',
	},
	committeeSection: {
		title: 'Organization',
		subtitle: '委員會成員',
		aboutTitle: 'TAICHI 台灣人機互動學會',
		aboutDescription: [
			'隨著電腦科學的快速發展與進步，電腦融入了人類日常生活的每個層面。人與電腦的溝通手段，人機互動的重要性也日益顯著。由於不同形式的電腦不斷的推陳出新，人機互動的研究不斷的出現新的機會與重要研究議題；其研究成果也常被應用於產業界的服務，與產品緊密結合。在各領域人機互動研究人員的共同努力下，國內人機互動的學術研究在這幾年蓬勃發展，其發表之研究成果也在國際學術領域中佔有一席之地。為了進一步促進台灣的人機互動研究與發展與交流，使其能夠更加繁榮、進步，2016 年春天，在人機互動產學界先進們的關注與支持之下，台灣人機互動學會於國立台灣大學資訊工程學系成立，並在同年夏初獲准設立。',
		],
		aboutButtonText: '學會網站',
		aboutButtonUrl: 'https://taiwanchi.org/',
		chairTitles: {
			'general chairs': { zh: '會議主席', en: 'GENERAL CHAIRS' },
			'steering committees': { zh: '指導委員', en: 'STEERING COMMITTEES' },
			'program chairs': { zh: '議程主席', en: 'PROGRAM CHAIRS' },
			'paper chairs': { zh: '論文主席', en: 'PAPER CHAIRS' },
			'poster chairs': { zh: '海報主席', en: 'POSTER CHAIRS' },
			'demo chairs': { zh: '展示主席', en: 'DEMO CHAIRS' },
			'panel chairs': { zh: '論壇主席', en: 'PANEL CHAIRS' },
			'workshop chairs': { zh: '工作坊主席', en: 'WORKSHOP CHAIRS' },
			'publicity chairs': { zh: '宣傳主席', en: 'PUBLICITY CHAIRS' },
			'performance chairs': { zh: '表演主席', en: 'PERFORMANCE CHAIRS' },
			'beer chairs': { zh: '酒吧主席', en: 'BEER CHAIRS' },
			'family chairs': { zh: '家庭主席', en: 'FAMILY CHAIRS' },
			'sponsor chairs': { zh: '贊助主席', en: 'SPONSOR CHAIRS' },
			'publication chairs': { zh: '出版主席', en: 'PUBLICATION CHAIRS' },
			'design competition chairs': { zh: '競賽主席', en: 'COMPETITION CHAIR' },
			'best paper award committee': { zh: '論文獎委員', en: 'BEST PAPER AWARD COMMITTEE' },
			'web chairs': { zh: '網路主席', en: 'WEB CHAIRS' },
			'visual chairs': { zh: '視覺主席', en: 'VISUAL CHAIRS' },
			'registration chairs': { zh: '註冊主席', en: 'REGISTRATION CHAIRS' },
			'student volunteer chairs': { zh: '學生志願主席', en: 'STUDENT VOLUNTEER CHAIRS' },
		},
	},
	competitionSection: {
		title: 'Competition',
		badge: 'COMING SOON',
		highlightTitle: '精彩競賽即將登場',
		description: 'TAICHI 2026 正在籌備精彩的競賽活動，敬請期待！相關資訊將於近期公佈，請密切關注官網更新。',
	},
	familyFriendlySection: {
		title: 'Family-Friendly',
		seoTitle: 'Family-Friendly',
		seoDescription: 'TAICHI 2026 歡迎攜帶家屬同行，打造更友善的參與現場。',
		introLines: [
			'歡迎攜伴、攜童或家人同行。',
			'今年特別設置 TAICHI-Kids 工作坊！',
			'讓孩子一起來 Big Bang!',
		],
		outroLine: '更多活動規劃將後續公告！敬請期待！',
	},
	keynoteSection: {
		title: 'KEYNOTE SPEAKERS',
		subtitle: '專題演講',
		tbd: '講者即將公布',
	},
	programSection: {
		title: 'AGENDA',
		subtitle: '會議時程',
		viewDetail: '場次 // ',
		backToIndex: '返回議程',
		viewProject: '場次 // ',
		agendaTba: '議程即將公布。',
		chairsLabel: '主席',
	},
	venueSection: {
		title: 'Venue',
		subtitle: '活動行程',
		submenuItems: [
			{ label: 'Overview', target: 'venue-overview' },
			{ label: '8/5', target: 'venue-day-1' },
			{ label: '8/6', target: 'venue-day-2' },
		],
		dayButtons: [{ label: '[ 8/5 ]', target: 'venue-day-1' }, { label: '[ 8/6 ]', target: 'venue-day-2' }],
		openMap: '開啟地圖',
		topButton: 'TOP',
		overview: {
			title: 'Overview',
			intro:
				'本屆 TAICHI 為一系列跨域大型活動的一部分（2026/08/03–08/06），與臺灣晶創人文計畫、國際亞洲區 APMAR、以及科技藝術學會 ISAT 共同串聯，打造橫跨學術、展演與公共參與的整體場域。8/3 至 8/4 由 APMAR 率先展開活動，8/5 四個單位共同對外開放，進行國際 keynote、互動市集與表演，8/6 則進入 TAICHI 研討會議程。',
			events: {
				preEvent: {
					date: '2026/08/03–04 [APMAR]',
					description: [
						'APMAR 將於 8/3 與 8/4 率先展開，以藝術研究、跨域實作與國際交流為核心，串接本屆 TAICHI 系列活動的前導內容。',
						'這裡可查看 APMAR 活動資訊與官網，了解完整議程與主辦內容。',
					],
					buttonLabel: '進入 APMAR 活動網站',
					buttonType: 'external',
					href: 'https://sites.google.com/view/apmar2026/',
					image: '/images/overview-02.jpg',
				},
				day1: {
					date: '2026/08/05 [TAICHI × 晶創人文 × APMAR × ISAT]',
					description: [
						'8/5 將於三創生活園區舉辦四單位聯合開放日，包含國際 keynote、互動夜市、展演與公眾參與活動。',
						'點擊下方按鈕可直接前往 8/5 的場地與活動資訊。',
					],
					buttonLabel: '查看 8/5 場地資訊',
					buttonType: 'section',
					target: 'venue-day-1',
					image: '/images/overview-03.jpg',
				},
				day2: {
					date: '2026/08/06 [TAICHI]',
					description: [
						'8/6 於國立臺北科技大學進行 TAICHI 年度研討會，聚焦論文發表、論壇與學術交流。',
						'點擊下方按鈕可直接前往 8/6 的場地與活動資訊。',
					],
					buttonLabel: '查看 8/6 場地資訊',
					buttonType: 'section',
					target: 'venue-day-2',
					image: '/images/overview-04.jpg',
				},
			},
			timeline: [
				{ label: '8/3', sublabel: 'APMAR', key: 'preEvent' },
				{ label: '8/4', sublabel: 'APMAR', key: 'preEvent' },
				{ label: '8/5', sublabel: 'TAICHI, 晶創人文 / APMAR, ISAT', key: 'day1' },
				{ label: '8/6', sublabel: 'TAICHI', key: 'day2' },
			],
		},
		days: [
			{
				id: 'venue-day-1',
				tabLabel: '[ 8/5 ]',
				heroImage: '/images/day1location.avif',
				heroTitle: '8/5(三) 互動夜市 [對外公開]',
				heroSubtitle: 'TAICHI、晶創人文、APMAR、ISAT 聯合活動',
				highlight: { label: '地點', venue: '臺北三創生活園區 5F 和 12F', details: ['5F 國際大咖 Keynote 演講連環場', '12F 互動夜市、小吃、表演揍作伙來'], note: '詳細行程表待公告。' },
				venues: [
					{ title: '5F 廳 [三創生活園區]', subtitle: 'Syntrend Creative Park, Taipei', addressLabel: '地址', addressZh: '100013 臺北市中正區市民大道三段 2 號', addressEn: 'No. 2, Sec. 3, Civic Blvd., Zhongzheng Dist., Taipei City 100013', venueLabel: '會議場地', venueName: '5F 廳提供 keynote 與論壇，滿滿大咖國際演講。', photoImage: '/images/day1_5F.jpg', mapLink: 'https://maps.app.goo.gl/yYLTdcVH5rSMevEF8', mapEmbedSrc: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3614.6633085538724!2d121.52874377537685!3d25.04549777780891!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3442a97b582d5a73%3A0x9b1e56ab48807d62!2z5LiJ5Ym155Sf5rS75ZyS5Y2A!5e0!3m2!1szh-TW!2stw!4v1772020903779!5m2!1szh-TW!2stw' },
					{ title: '12F 多元展演廳 [三創生活園區]', subtitle: 'Syntrend Creative Park, Taipei', addressLabel: '地址', addressZh: '100013 臺北市中正區市民大道三段 2 號', addressEn: 'No. 2, Sec. 3, Civic Blvd., Zhongzheng Dist., Taipei City 100013', venueLabel: '會議場地', venueName: '互動夜市、小吃、表演。', photoImage: '/images/day1_12F.jpg', mapLink: 'https://maps.app.goo.gl/yYLTdcVH5rSMevEF8', mapEmbedSrc: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3614.6633085538724!2d121.52874377537685!3d25.04549777780891!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3442a97b582d5a73%3A0x9b1e56ab48807d62!2z5LiJ5Ym155Sf5rS75ZyS5Y2A!5e0!3m2!1szh-TW!2stw!4v1772020903779!5m2!1szh-TW!2stw' },
				],
				travelPanels: [
					{ title: '大眾運輸', items: [{ title: '捷運 MRT', lines: ['板南線 / 忠孝新生站 1 號出口，步行約 3 分鐘', '新蘆線 / 忠孝新生站 1 號出口，步行約 3 分鐘'] }, { title: '公車 Bus', lines: ['三創生活園區、光華商場周邊站牌，多條路線可達'] }] },
					{ title: '自行開車', items: [{ title: '停車資訊', lines: ['三創生活園區停車場', '光華數位新天地周邊停車場', '建國高架橋下停車場'] }], calloutTitle: '建議', callout: '活動時段人潮較多，建議優先搭乘大眾運輸工具。' },
				],
			},
			{
				id: 'venue-day-2',
				tabLabel: '[ 8/6 ]',
				heroImage: '/images/day2location.avif',
				heroTitle: '8/6(四) 年度研討會',
				heroSubtitle: 'TAICHI 年度學會研討會',
				highlight: { label: '地點', venue: '國立臺北科技大學', details: ['論文發表與論壇講座'], note: '詳細議程與場地配置將陸續公告。' },
				venues: [
					{ title: '國際演講廳 [臺北科技大學]', subtitle: 'National Taipei University of Technology, Taipei', addressLabel: '地址', addressZh: '10608 臺北市大安區忠孝東路三段 1 號', addressEn: "No. 1, Sec. 3, Zhongxiao E. Rd., Da'an Dist., Taipei City 10608", venueLabel: '會議場地', venueName: '論文發表、講座。', photoImage: '/images/day2_X.avif', mapLink: 'https://maps.app.goo.gl/p97U3oZnXoUvrXmo7', mapEmbedSrc: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d903.6783181717664!2d121.53284755506823!3d25.043802836933057!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3442a97d255598df%3A0x47ea748e8f3f53aa!2z5ZyL56uL6Ie65YyX56eR5oqA5aSn5a24!5e0!3m2!1szh-TW!2stw!4v1772020528494!5m2!1szh-TW!2stw' },
				],
				travelPanels: [
					{ title: '大眾運輸', items: [{ title: '捷運 MRT', lines: ['板南線 / 忠孝新生站 4 號出口，步行約 5 分鐘', '文湖線 / 忠孝復興站轉乘，步行或公車前往'] }, { title: '高鐵 HSR / 台鐵 TRA', lines: ['台北車站下車後轉乘捷運板南線至忠孝新生站'] }, { title: '公車 Bus', lines: ['正義郵局、臺北科技大學周邊站牌，多條路線可達'] }] },
					{ title: '自行開車', items: [{ title: '停車資訊', lines: ['北科大周邊停車場', '建國高架橋下停車場', '臺北科技大學周邊收費停車格'] }], calloutTitle: '建議', callout: '校園周邊停車位有限，建議提前抵達或改搭捷運前往。' },
				],
			},
		],
	},
	sponsorsSection: {
		mainOrganizers: '主辦單位',
		coOrganizersTitle: '共同主辦',
		organizers: [
			{ name: '台灣人機互動學會', logo: '/logos/taichi.webp', size: 'large', className: 'px-8 py-5 rounded-3xl shadow-2xl' },
			{ name: '國科會晶創人文計畫', logo: '/logos/NSTC_.png', size: 'large', className: 'px-8 py-5 rounded-3xl shadow-2xl' },
		],
		coOrganizers: [
			{ name: '國立臺灣科技大學', logo: '/logos/NTUST.png', size: 'small', className: 'px-6 py-4 rounded-2xl shadow-xl' },
			{ name: '國立臺北科技大學', logo: '/logos/NTUT.png', size: 'S', className: 'px-6 py-4 rounded-2xl shadow-xl' },
		],
		supportingOrganizersTitle: '協辦單位',
		supportingOrganizers: [
			{ name: '台灣科技藝術學會', logo: '/logos/ISAT.png', size: 'small', className: 'px-6 py-4 rounded-2xl shadow-xl' },
			{ name: 'APMAR', logo: '/logos/APMAR.png', size: 'small', className: 'px-6 py-4 rounded-2xl shadow-xl' },
		],
		sponsorsTitle: '贊助單位',
		sponsors: [
			{ name: '美國在台協會', logo: '/logos/AIT.png', size: 'large', className: 'px-6 py-4 rounded-2xl shadow-xl' },
			{ name: '美國創新中心', logo: '/logos/AIC.png', size: 'large', className: 'px-6 py-4 rounded-2xl shadow-xl' },
		],
	},
	footer: {
		title: 'TAICHI 2026 \n BIG BANG! FUTURE!',
		socialsTitle: 'FOLLOW US',
		facebook: 'https://www.facebook.com/taiwanchi',
		locationsTitle: 'CONTACT',
		locationsList: ['taiwanchi26@gmail.com', 'Taipei, Taiwan'],
		copyright: 'COPYRIGHT © 2026 TAICHI',
		credits: '',
	},
	contact: CONFIG.contact,
} as const;
