import { CONTENT_ZH } from './content.zh';

export const CONTENT_EN = {
	...CONTENT_ZH,
	meta: {
		title: 'TAICHI 2026 | Big Bang Future',
		description: 'The 12th Annual Conference of TAICHI. Theme: Big Bang! Futures!',
		url: 'https://taichi2026.taiwanchi.org',
	},
	nav: {
		...CONTENT_ZH.nav,
		home: 'HOME',
		news: 'NEWS',
		theme: 'THEME',
		program: 'AGENDA',
		keynotes: 'KEYNOTES',
		registration: 'REGISTRATION',
		notion: 'DB ADMIN',
	},
	heroBanner: {
		topText: 'The 12th Annual Conference of TAICHI',
		bottomText: '2026/8/5 - 8/6 TAIPEI, TAIWAN',
	},
	submissionDeadline: {
		title: 'SUBMISSION DEADLINE',
		date: '2026/6/23 Tue. 23:59 (GMT+8)',
		buttonText: 'SUBMIT NOW',
	},
	theme: {
		title: 'TAICHI2026 Theme: Big Bang! Futures!',
		slogan: "The future doesn't whisper; it bangs!",
		description:
			'Big Bang! Futures is inspired by the universe’s first spark, when explosion, energy, and life began. We bring that moment into the city as a future the public can walk through, play with, and experience together. Through interactive works, experimental pieces, and a night-market atmosphere, visitors are invited to explore how technology shapes future ways of living, gathering, and relating.',
	},
	cfpSection: {
		...CONTENT_ZH.cfpSection,
		subtitle: 'SUBMISSION INFO',
		topicsTitle: 'Conference Topics',
		importantDatesTitle: 'Important Date',
		heroDeadlineNote: 'Submission deadline: 2026/06/23 23:59 (GMT+8)',
		heroTimelineItems: [
			{ title: 'DEADLINE', date: '06.23', oldDate: '06.18', subtitle: 'Submission deadline' },
			{ title: 'NOTIFICATION', date: '07.21', oldDate: '', subtitle: 'Review results announced' },
			{ title: 'CAMERA-READY DEADLINE', date: '07.27', oldDate: '', subtitle: 'Final camera-ready due' },
			{ title: 'CONFERENCE', date: '08.05-06', oldDate: '', subtitle: 'Conference dates' },
		],
		categories: [
			{
				...CONTENT_ZH.cfpSection.categories[0],
				title: 'Full Paper & Pictorial',
				description: [
					'Papers are the primary venue for presenting complete and unpublished new research contributions. Accepted submissions will be scheduled in the conference program. Papers may be submitted in either Chinese or English, and all submissions should follow the ACM SIGCHI two-column paper format or the DIS pictorial format.',
					'Full Paper',
					'Please download the Full Paper submission templates from the official ACM CHI/UIST/DIS websites. Authors should choose the template that matches their preferred authoring tool from the links below:',
					'● [Latex Template](https://portalparts.acm.org/hippo/latex_templates/acmart-primary.zip)',
					'● [Overleaf Template](https://www.overleaf.com/latex/templates/acm-conference-proceedings-primary-article-template/wbvnghjbzwpc)',
					'● [Microsoft Word for Windows](https://www.acm.org/binaries/content/assets/publications/word_style/interim-template-style/interim-layout.docx)',
					'For additional details, please refer to the [ACM Template](https://www.acm.org/publications/proceedings-template) guide. TAICHI Full Papers should normally be **8 to 12 pages and no more than 12 pages** excluding references. For Chinese submissions, please use DFKai-SB and keep the same font size settings as the English paper format, following the ACM SIGCHI formatting guidelines.',
					'Pictorial',
					'For pictorial submissions, please prepare the manuscript according to the [ACM DIS2025](https://dis.acm.org/2025/call-for-pictorials/) guidelines. The template links below are provided for different editing tools:',
					'● [Pictorials InDesign Template](https://dis.acm.org/2025/wp-content/uploads/2024/11/DIS2021-Pictorials-InDesign-template_Folder.zip)',
					'● [Pictorials Word Template](https://dis.acm.org/2025/wp-content/uploads/2024/11/DIS2021-Pictorials-Word-template-Folder.zip)',
					'● [Pictorials Powerpoint Template](https://dis.acm.org/2025/wp-content/uploads/2024/11/DIS2021-Pictorials-PowerPoint-template-Folder.zip)',
					'TAICHI pictorials should normally be **8 to 12 pages and no more than 12 pages** excluding references. Please use the standard first-page layout. For Chinese submissions, use DFKai-SB and keep the same font size settings as the English paper format. All other pages may use a freer layout while still following ACM SIGCHI requirements.',
					'Notes',
					'● All submissions use **double-blind review**. Please upload an anonymized PDF file; non-anonymized submissions will be desk rejected. The PDF including attachments must be **under 20MB**. Please optimize the file in Acrobat while keeping the content clearly legible on screen.',
					'● Accepted papers will be included in the informal TAICHI 2026 online proceedings for download. Authors who prefer not to include the full paper may instead choose to have an abstract version included in the informal proceedings.',
					'● Whether a submitted paper may be converted to a poster after review will depend on the overall submission volume; authors are encouraged to submit in the format best suited to their work.',
					'Desk Reject Policy',
					'● If a submission is out of scope, has unclear or incomplete contributions, or does not follow the required format, the organizers reserve the right to conduct an initial screening and directly reject the paper before review (desk reject). Possible cases include:',
					'● ● __Scope__：The submission does not sufficiently review relevant literature or provide enough context to explain its novelty and contribution to design research or interactive systems. The paper should be grounded in prior research, design practice, or relevant domains, and its contribution should be commensurate with its length.',
					'● ● __Methodology__：The submission does not provide enough information about its methods and process, such as an unclear conceptual framework, incomplete argumentation, or insufficient methodological description and research transparency.',
					'● ● __Data__：The submission lacks sufficient data or evidence to support its analysis and claims, making its conclusions difficult to verify.',
					'Paper Chairs',
					'Yaliang Chuang / 莊雅量 / Department of Arts and Design, National Tsing Hua University',
					'Shan Yuan Teng / 鄧善元 / Department of Computer Science and Information Engineering, National Taiwan University',
					'Hsin-Ruey (Ray) Tsai / 蔡欣叡 / Department of Computer Science, National Chengchi University',
					'Yu-Chun (Grace) Yen / 顏羽君 / Department of Computer Science, National Yang Ming Chiao Tung University',
					'For paper submissions, please contact [taiwanchi26+paper@gmail.com](mailto:taiwanchi26+paper@gmail.com)',
				],
			},
			{
				...CONTENT_ZH.cfpSection.categories[1],
				title: 'Poster',
				description: [
					'Posters provide an opportunity for authors and conference participants to directly discuss work in progress or research that has already been presented at other venues. Accepted posters will be presented during the conference poster session, and at least one author must attend the conference and stand by the poster during the assigned session.',
					'Submission Format',
					'● Submissions should follow the ACM SIGCHI Publication Format (two-column) and must be submitted as a PDF.',
					'● Templates: [Latex](https://portalparts.acm.org/hippo/latex_templates/acmart-primary.zip), [Overleaf](https://www.overleaf.com/latex/templates/acm-conference-proceedings-primary-article-template/wbvnghjbzwpc), [Word](https://uist.acm.org/2023/assets/files/word-two-column-submission-sample.docx)',
					'● TAICHI poster papers should normally be **4 pages** excluding references.',
					'● The paper should include an abstract, motivation, objective, method, current results, and a future research plan.',
					'● Only the paper needs to be uploaded at submission time. The poster file will be requested after acceptance.',
					'● All accepted posters will be considered for the Poster Paper Award, selected by anonymous voting from conference participants.',
					'Notes',
					'● Poster submissions use **non-anonymous review**. Please include all required author information in the paper. Please upload a non-anonymized PDF file; submissions without author information will be desk rejected.',
					'● The PDF including attachments must be under 20MB. Please optimize the file in Acrobat while keeping the content clearly legible on screen.',
					'● Accepted poster papers will be included in the informal TAICHI 2026 online proceedings for download. Authors who have concerns about full-paper inclusion may choose to have an abstract version included instead.',
					'● If the topic is outside the conference scope, the contribution is unclear or incomplete, or the paper does not follow the required format, the organizers reserve the right to desk reject the submission before review. Please refer to the Full Paper and Pictorial criteria.',
					'● TAICHI 2026 will be co-located with international events, and posters in English are strongly encouraged.',
					'Poster Chairs',
					'Chiu-Hsuan Wang / 王秋玄 / Postdoctoral Researcher, Department of Information Management, National Taiwan University',
					'Fu-Yin Cherng / 程芙茵 / Assistant Professor, Department of Computer Science and Information Engineering, National Cheng Kung University',
					'Wei-Ming Chung / 莊偉銘 / Lecturer, Department of Product Design, Ming Chuan University',
					'● For poster submissions, please contact [taiwanchi26+poster@gmail.com](mailto:taiwanchi26+poster@gmail.com)',
				],
			},
			{
				...CONTENT_ZH.cfpSection.categories[2],
				title: 'Interactivity and Demo',
				description: [
					'Demo submissions present implemented interactive concepts, techniques, devices, or systems directly at the conference. Accepted demos may be exhibited in booth format during the demo session.',
					'Submission Format',
					'● Submissions should follow the ACM SIGCHI Extended Abstract format and must be submitted as a PDF. Anonymization is not required. Please download the standard format from the ACM SIGCHI official CHI Publication Formats website.',
					'● Templates: [Latex](https://portalparts.acm.org/hippo/latex_templates/acmart-primary.zip), [Overleaf](https://www.overleaf.com/latex/templates/acm-conference-proceedings-primary-article-template/wbvnghjbzwpc), [Word](https://uist.acm.org/2023/assets/files/word-two-column-submission-sample.docx)',
					'● The submission is limited to **3 pages maximum** excluding references, using a **two-column layout**. Submissions may be written in Chinese or English. For Chinese text, please use DFKai-SB.',
					'● The paper should include an abstract, motivation, objective, method, current results, and a future research plan.',
					'● The title should begin with “Demo:”. If it is also a poster, use “Poster & Demo:”.',
					'● Authors are encouraged to upload a video so the interaction quality and system completeness can be better evaluated. Please compress the video with HandBrake and export it as an H.264 `.mp4` file before upload.',
					'● A completed “[Venue Requirement Form](https://docs.google.com/document/d/1uMsKeIa64dYQAFFQLggcIR7leRA1TC7Jc2RsYja3YTY)” must also be submitted. The demo chairs will use it to coordinate booth setup arrangements for the event day.',
					'● All accepted demos will be considered for the Demo Paper Award, selected by anonymous voting from conference participants.',
					'Notes',
					'● Accepted demos will be included in the informal TAICHI 2026 online proceedings for download. Authors who have concerns about full-paper inclusion may choose to have an abstract version included instead.',
					'● Please complete booth setup before the demo session begins on site.',
					'● TAICHI 2026 will be co-located with other international events, and presenting demo-related posters in English is encouraged.',
					'Demo Chairs',
					'Ching-Wen Hung / 洪靖雯 / PhD Candidate, Graduate Institute of Networking and Multimedia, National Taiwan University',
					'● For demo submissions, please contact [taiwanchi26+demo@gmail.com](mailto:taiwanchi26+demo@gmail.com)',
				],
			},
		],
	},
	newsSection: {
		...CONTENT_ZH.newsSection,
		subtitle: 'LATEST ANNOUNCEMENTS',
		loadMore: 'LOAD MORE',
		showLess: 'SHOW LESS',
		readMore: 'READ MORE',
		viewAll: 'VIEW ALL NEWS',
	},
	committeeSection: {
		...CONTENT_ZH.committeeSection,
		subtitle: 'COMMITTEE MEMBERS',
		aboutTitle: 'About TAICHI',
		aboutDescription: [
			'As computer science continues to rapidly evolve, computing has become embedded in every aspect of everyday life. The ways people communicate with computers have expanded, and the importance of human-computer interaction has grown accordingly. Because new forms of computing continue to emerge, HCI research constantly opens up new opportunities and important questions. Its findings are closely connected to industry services and products. Through the collective efforts of researchers across many domains, HCI scholarship in Taiwan has flourished and gained international visibility. To further promote research, development, and exchange in Taiwan, the Taiwan Association of Human-Computer Interaction was established in spring 2016 at the Department of Computer Science and Information Engineering, National Taiwan University, and formally approved in early summer of the same year.',
		],
		aboutButtonText: 'Association Website',
	},
	competitionSection: {
		title: 'COMPETITION',
		badge: 'COMING SOON',
		highlightTitle: 'Competition Details Coming Soon',
		description: 'TAICHI 2026 is preparing a new competition program. More details will be announced soon, so please stay tuned to the official website.',
	},
	familyFriendlySection: {
		...CONTENT_ZH.familyFriendlySection,
		seoDescription:
			'TAICHI 2026 welcomes family-accompanied participation and supports a more inclusive on-site experience.',
		headline: 'TAICHI 2026 Welcomes Families: Introducing Our First Family-Friendly Initiative',
		paragraphs: [
			'TAICHI 2026 warmly welcomes all attendees, and we are delighted to welcome your families as well.',
			'Our families are a source of support, inspiration, and strength. Whether they are partners, children, or parents, they accompany us through our journeys in research, work, and everyday life. For TAICHI, inviting families to be part of this academic gathering is both a natural and meaningful step.',
			'This year, TAICHI 2026 is launching its first family-friendly initiative, designed to help attendees who are coming with family members participate in the conference with greater peace of mind. We will provide a family-friendly space with areas for rest, companionship, and simple play activities. We will also prepare light activities for children who may be curious about what their parents or family members do in their research and professional lives. In addition, family-friendly seating will be reserved in the conference rooms to offer greater flexibility for attendees with caregiving needs.',
			'We will also provide a brief family-friendly guide to the area around the venue, helping you locate nearby parks, pharmacies, convenient facilities, and quiet places for short breaks.',
			'This is TAICHI’s first step toward creating a more family-friendly conference experience. Through this new initiative, we hope to make our academic community more closely connected to the realities of everyday life, and to support more researchers in participating fully in the conference. If you plan to attend with family members, please let us know through the registration form so that we can better prepare in advance.',
			'We look forward to welcoming you and your family to TAICHI 2026.',
		],
		surveyHeading: 'TAICHI 2026 Family Attendance Survey',
		surveyDescription:
			'If you plan to attend with family members, please fill out this short survey so we can prepare in advance.',
		surveyButtonText: 'Open Survey Form',
		outroLine: 'More family-friendly activities will be announced soon. Stay tuned!',
	},
	sponsorshipSection: {
		...CONTENT_ZH.sponsorshipSection,
		seoTitle: 'Sponsorship',
		seoDescription:
			'TAICHI 2026 sincerely invites companies and organizations to support the 12th Taiwan CHI conference. Download the full sponsorship invitation and prospectus.',
		pageTitle: 'Sponsorship',
		kicker: 'TAICHI 2026 SPONSORSHIP',
		headline: 'Let’s make the future go Big Bang!',
		paragraphs: [
			'TAICHI 2026 takes place on August 5–6 at Syntrend Creative Park and National Taipei University of Technology in Taipei. This year’s theme, “Big Bang! Futures”, brings the universe’s first explosive moment into the city — a future you can walk through, play with, and experience together, through interactive installations, experimental works, and a night-market-style space where everyone can feel how technology shapes the way we’ll live.',
			'This year is different: on August 5 we join forces at Syntrend with the NSTC Taiwan Chip-based Humanities initiative, the Asia-Pacific APMAR, and the technology-art society ISAT — bringing academia, exhibition, and the public together in one shared field, with a large turnout of scholars, industry partners, and the public expected.',
			'TAICHI is the Taiwan HCI community’s most important annual gathering, held every year since 2015 and drawing hundreds of scholars, industry partners, and students. Our members’ work regularly appears at top international venues such as CHI, UIST, CSCW, Ubicomp, and DIS.',
			'We warmly invite you to become a sponsor this year — to put your brand alongside some of the most creative people around, and make Taiwan’s future experience go Big Bang together. The sponsorship plans are below; we look forward to partnering with you.',
		],
		highlightsTitle: 'Event Highlights',
		highlights: [
			{ label: 'DATE', value: 'Aug 5 – 6, 2026' },
			{ label: 'VENUE', value: 'Syntrend Creative Park × NTUT' },
			{ label: 'THEME', value: 'Big Bang! Futures' },
			{ label: 'CO-HOSTED', value: 'Chip-based Humanities × APMAR × ISAT' },
			{ label: 'COMMUNITY', value: 'Hundreds of scholars, industry & students yearly' },
		],
		plansTitle: 'Sponsorship Plans',
		plansIntro:
			'The following sponsorship plans are available. If none fits your organization’s needs, you are welcome to contact us to discuss other options.',
		tierNames: ['Diamond', 'Platinum', 'Gold', 'Silver'],
		planRows: [
			{ label: 'Amount (NT$)', values: ['80,000', '50,000', '30,000', '15,000'] },
			{ label: 'Complimentary tickets', values: ['8', '6', '3', '2'] },
			{ label: 'Logo on conference website', values: ['✓', '✓', '✓', '✓'] },
			{
				label: 'On-site logo display',
				values: ['Stage, podium, registration & venue signage', 'Stage, podium, registration & venue signage', 'Stage, podium, registration & venue signage', 'Stage, podium, registration & venue signage'],
			},
			{ label: 'Online handbook (program) logo', values: ['Logo + promo copy', 'Logo + promo copy', 'Logo + promo copy', 'Logo only'] },
			{ label: 'Dedicated exhibition booth', values: ['1 set / 2 booths', '1 set / 1 booth', '1 set / 1 booth', '—'] },
			{ label: 'Flyer at registration desk', values: ['✓', '✓', '✓', '—'] },
			{ label: 'On-site video rotation', values: ['✓ (30 sec)', '✓ (10 sec)', '✓ (5 sec)', '—'] },
			{ label: 'Aug 5 Interactive Night Market', values: ['Logo + stage intro (8 min)', 'Logo + stage intro (5 min)', 'Logo display', '—'] },
		],
		plansNoteTitle: 'Notes',
		plansNotes: [
			'Please contact the organizing team to confirm sponsorship items before completing the sponsorship agreement.',
			'Please complete payment within one week of confirming your sponsorship items so promotional preparations can proceed.',
			'Plans and on-site space are limited; the organizers reserve related decisions on a first-paid, first-served basis.',
		],
		pdfHeading: 'Full Sponsorship Invitation & Prospectus',
		pdfDescription: 'Sponsorship tiers, benefits, and how to sign up are detailed in the full document. You are welcome to download it.',
		pdfButtonText: 'Download Sponsorship Prospectus (PDF)',
		processTitle: 'Sponsorship Process',
		processSteps: [
			{
				title: 'Step 1 | Confirm sponsorship items',
				body: [
					'Sponsorship contact: Max Chen, Dept. of Information Management, Ming Chuan University | 0952-702363 | maxchen@mail.mcu.edu.tw',
					'Payment contact: June Lai, Taiwan CHI society | 02-33664888 ext. 503 | june@cmlab.csie.ntu.edu.tw',
				],
			},
			{
				title: 'Step 2 | Send the sponsorship agreement',
				body: ['Email or fax the [Sponsorship Agreement] to June Lai (june@cmlab.csie.ntu.edu.tw) and Max Chen (maxchen@mail.mcu.edu.tw).'],
			},
			{
				title: 'Step 3 | Make payment',
				body: ['Account name: Taiwan Association for Computer-Human Interaction', 'Bank: Hua Nan Commercial Bank (code 008)', 'Account no.: 154-10-009173-1'],
			},
			{
				title: 'Step 4 | Payment notification',
				body: [
					'After payment, email June Lai (june@cmlab.csie.ntu.edu.tw) and Max Chen (maxchen@mail.mcu.edu.tw) with:',
					'1. The last five digits of the paying account',
					'2. The name and phone number of the paying company’s contact person',
				],
			},
		],
		contactHeading: 'Sponsorship Inquiries',
		contactText: 'For any sponsorship-related questions, please contact the organizing team:',
	},
	keynoteSection: {
		title: 'KEYNOTE SPEAKERS',
		subtitle: 'INVITED TALKS',
		tbd: 'Speakers TBD',
	},
	programSection: {
		title: 'AGENDA',
		subtitle: 'CONFERENCE SCHEDULE',
		viewDetail: 'SESSION // ',
		backToIndex: 'BACK TO AGENDA',
		viewProject: 'SESSION // ',
		agendaTba: 'Agenda to be announced.',
		chairsLabel: 'Chairs',
	},
	venueSection: {
		...CONTENT_ZH.venueSection,
		subtitle: 'VENUE PLAN',
		openMap: 'OPEN MAP',
		overview: {
			title: 'Overview',
			intro:
				'TAICHI 2026 is part of a larger cross-disciplinary event series running from 2026/08/03 to 2026/08/06, co-organized with the Program on Semiconductors and Humanities, APMAR, and ISAT. Together, these events shape one connected field spanning research, exhibition, performance, and public participation. APMAR begins on 8/3 and 8/4, the four organizations jointly open to the public on 8/5, and TAICHI continues with the conference program on 8/6.',
			events: {
				preEvent: {
					date: '2026/08/03–04 [APMAR]',
					description: [
						'APMAR opens the series on 8/3 and 8/4 with a program centered on artistic research, interdisciplinary practice, and international exchange.',
						'Use the link below to view the official APMAR program and website.',
					],
					buttonLabel: 'Open APMAR Website',
					buttonType: 'external',
					href: 'https://sites.google.com/view/apmar2026/',
					image: '/images/overview-02.jpg',
				},
				day1: {
					date: '2026/08/05 [TAICHI × Semiconductors and Humanities × APMAR × ISAT]',
					description: [
						'On 8/5, Syntrend Creative Park hosts the joint public day featuring international keynotes, an interactive night market, performances, and open participation.',
						'Use the button below to jump to the 8/5 venue details.',
					],
					buttonLabel: 'View 8/5 Venue Details',
					buttonType: 'section',
					target: 'venue-day-1',
					image: '/images/overview-03.jpg',
				},
				day2: {
					date: '2026/08/06 [TAICHI]',
					description: [
						'On 8/6, National Taipei University of Technology hosts the TAICHI annual conference with paper presentations, forums, and academic exchange.',
						'Use the button below to jump to the 8/6 venue details.',
					],
					buttonLabel: 'View 8/6 Venue Details',
					buttonType: 'section',
					target: 'venue-day-2',
					image: '/images/overview-04.jpg',
				},
			},
			timeline: [
				{ label: '8/3', sublabel: 'APMAR', key: 'preEvent' },
				{ label: '8/4', sublabel: 'APMAR', key: 'preEvent' },
				{ label: '8/5', sublabel: 'TAICHI, Semiconductors and Humanities / APMAR, ISAT', key: 'day1' },
				{ label: '8/6', sublabel: 'TAICHI', key: 'day2' },
			],
		},
		days: [
			{
				...CONTENT_ZH.venueSection.days[0],
				heroTitle: '8/5(Wed): Night Market [Open Public]',
				heroSubtitle: 'Joint event by TAICHI, Program on Semiconductors and Humanities, APMAR, and ISAT',
				highlight: {
					label: 'Venue',
					venue: 'Syntrend Creative Park, 5F and 12F',
					details: ['5F international keynote talks', '12F interactive night market, snacks, and Live Coding performances'],
					note: 'Detailed schedule will be announced soon.',
				},
				venues: [
					{ ...CONTENT_ZH.venueSection.days[0].venues[0], title: '5F Hall [Syntrend Creative Park]', addressLabel: 'Address', venueLabel: 'Venue', venueName: '5F Hall hosts international keynote talks.' },
					{ ...CONTENT_ZH.venueSection.days[0].venues[1], title: '12F Multi-Function Hall [Syntrend Creative Park]', addressLabel: 'Address', venueLabel: 'Venue', venueName: 'Interactive night market, snacks, and Live Coding performances.' },
				],
				travelPanels: [
					{ title: 'Public Transportation', items: [{ title: 'MRT', lines: ['Bannan Line / Zhongxiao Xinsheng Station Exit 1, about a 3-minute walk', 'Zhonghe-Xinlu Line / Zhongxiao Xinsheng Station Exit 1, about a 3-minute walk'] }, { title: 'Bus', lines: ['Multiple routes stop near Syntrend Creative Park and Guanghua Market'] }] },
					{ title: 'Driving', items: [{ title: 'Parking', lines: ['Syntrend parking lot', 'Parking lots near Guanghua Digital Plaza', 'Jianguo elevated roadway parking'] }], calloutTitle: 'Recommendation', callout: 'Public transport is recommended. If driving, allow extra time for parking and queues.' },
				],
			},
			{
				...CONTENT_ZH.venueSection.days[1],
				heroTitle: '8/6(Thu): Annual Conference',
				heroSubtitle: 'TAICHI annual conference',
				highlight: { label: 'Venue', venue: 'National Taipei University of Technology', details: ['Paper presentations and forum sessions'], note: 'Detailed agenda and room allocation will be announced soon.' },
				venues: [{ ...CONTENT_ZH.venueSection.days[1].venues[0], title: 'International Lecture Hall [National Taipei University of Technology]', addressLabel: 'Address', venueLabel: 'Venue', venueName: 'Paper presentations and talks.' }],
				travelPanels: [
					{ title: 'Public Transportation', items: [{ title: 'MRT', lines: ['Bannan Line / Zhongxiao Xinsheng Station Exit 4, about a 5-minute walk', 'Transfer from Wenhu Line at Zhongxiao Fuxing and continue on foot or by bus'] }, { title: 'HSR / TRA', lines: ['From Taipei Main Station, transfer to the Bannan Line and exit at Zhongxiao Xinsheng'] }, { title: 'Bus', lines: ['Multiple routes stop near Zhengyi Post Office and NTUT'] }] },
					{ title: 'Driving', items: [{ title: 'Parking', lines: ['Parking lots around NTUT', 'Jianguo elevated roadway parking', 'Street parking near the campus'] }], calloutTitle: 'Recommendation', callout: 'Parking near the campus is limited. Consider arriving early or taking the MRT.' },
				],
			},
		],
	},
	sponsorsSection: {
		...CONTENT_ZH.sponsorsSection,
		mainOrganizers: 'Main Organizers',
		coOrganizersTitle: 'Co-Organizers',
		supportingOrganizersTitle: 'Supporting Organizations',
		sponsorsTitle: 'Sponsors',
	},
	footer: {
		...CONTENT_ZH.footer,
		socialsTitle: 'FOLLOW US',
		locationsTitle: 'CONTACT',
	},
} as const;
