import { CONFIG } from './content.shared';

export const CONTENT_ZH = {
	meta: {
		title: 'TAICHI 2026 | Big Bang! Futures!',
		description: '第 12 屆台灣人機互動研討會。主題：Big Bang! Futures!',
		url: 'https://taichi2026.taiwanchi.org',
	},
	nav: {
		logo: 'TAICHI 2026',
		home: 'HOME',
		news: 'NEWS',
		theme: 'THEME',
		program: 'PROGRAM',
		keynotes: 'KEYNOTES',
		organization: 'ORGANIZATION',
		orgSponsors: 'ORGANIZATION & SPONSORS',
		cfp: 'CALL FOR PAPERS',
		familyFriendly: 'FAMILY-FRIENDLY',
		venue: 'VENUE',
		sponsors: 'SPONSORS',
		registration: 'REGISTRATION',
		notion: 'DB ADMIN',
		notionUrl: 'https://www.notion.so/',
		cfpSubmenu: [
			{ label: 'Important Date', hash: '#important-dates' },
			{ label: 'Themes', hash: '#themes' },
			{ label: 'Paper & Pictorial', hash: '#papers' },
			{ label: 'Poster', hash: '#posters' },
			{ label: 'Demo', hash: '#demos' },
		],
	},
	heroBanner: {
		topText: ' ',
		bottomText: ' ',
	},
	submissionDeadline: {
		title: '投稿截止日期',
		date: '2026/6/23（二）23:59 (GMT+8)',
		buttonText: '立即投稿',
	},
	theme: {
		title: 'TAICHI2026：Big Bang! Futures!',
		slogan: '未來將不再以低語傳遞，而是以爆炸式發生。',
		description:
			'第12屆台灣人機互動研討會主題「Big Bang! Futures」源自宇宙霹靂般的起始瞬間，象徵想法快速擴散、改變世界的一刻。我們將這個瞬間帶進城市，化為一個可以逛、可以玩、可以一起參與的未來現場，透過互動裝置、實驗作品與夜市般的體驗空間，邀請民眾親身感受並討論科技如何影響未來生活與彼此之間的關係，讓多重未來在連鎖爆發中持續 Big Bang！',
	},
	cfpSection: {
		title: 'Call For Papers',
		subtitle: '投稿資訊',
		topicsTitle: '研討會主題',
		importantDatesTitle: '重要時程',
		submissionLink: 'https://easychair.org/conferences/?conf=taichi2026',
		heroDeadlineNote: '截投稿截止日期: 2026/06/23 23:59 (GMT+8)',
		heroTimelineItems: [
			{ title: 'DEADLINE', date: '06.23', oldDate: '06.18', subtitle: '投稿截止日期' },
			{ title: 'NOTIFICATION', date: '07.21', oldDate: '', subtitle: '審查結果通知' },
			{ title: 'CAMERA-READY DEADLINE', date: '07.27', oldDate: '', subtitle: '最終完稿截止日期' },
			{ title: 'CONFERENCE', date: '08.05-06', oldDate: '', subtitle: '會議日期' },
		],
		exploreMore: 'EXPLORE MORE',
		topics: [
			{ en: 'Usability and User Experience', ch: '可用性與使用者體驗' },
			{ en: 'Interaction Techniques and Devices', ch: '互動技術與裝置' },
			{ en: 'Understanding Users and Human Behavior', ch: '理解使用者與人類行為' },
			{ en: 'Design Methods and Processes', ch: '設計方法與流程' },
			{ en: 'Mobile and Ubiquitous Computing', ch: '移動與普適計算' },
			{ en: 'Virtual, Augmented, Mixed, and Extended Reality (VR, AR, MR, XR)', ch: '虛擬、擴增、混合與擴展實境' },
			{ en: 'Human-AI Interaction', ch: '人工智慧與人類互動' },
			{ en: 'Social Computing and Collaboration', ch: '社群運算與協作' },
			{ en: 'Ethics, Accessibility, and Inclusive Design', ch: '倫理、無障礙與包容性設計' },
			{ en: 'More-than-Human Design', ch: '超越人本中心的設計' },
			{ en: 'Specific Application Areas', ch: '特定應用領域 (如學習、健康、家居、設計輔具等)' },
		],
		categories: [
			{
				id: 'papers',
				title: '論 文 與 圖 像 式 論 文',
				date: '2026/6/23(二) 23:59 (GMT+8)',
				oldDate: '2026/6/18(四)',
				notification: '2026/7/21(二) 23:59 (GMT+8)',
				cameraReady: '2026/7/27(一) 23:59 (GMT+8)',
				links: [
					{ label: 'Latex Template', url: 'https://portalparts.acm.org/hippo/latex_templates/acmart-primary.zip' },
					{ label: 'Overleaf Template', url: 'https://www.overleaf.com/latex/templates/acm-conference-proceedings-primary-article-template/wbvnghjbzwpc' },
					{ label: 'Microsoft Word for Windows', url: 'https://www.acm.org/binaries/content/assets/publications/word_style/interim-template-style/interim-layout.docx' },
					{ label: 'Macintosh Office 2011', url: 'https://portalparts.acm.org/hippo/enhanced_word_templates/MAC_2011/mac_2011.zip' },
					{ label: 'Macintosh Office 2016', url: 'https://portalparts.acm.org/hippo/enhanced_word_templates/MAC_2016/mac_2016.zip' },
					{ label: 'Pictorials InDesign Template', url: 'https://dis.acm.org/2025/wp-content/uploads/2024/11/DIS2021-Pictorials-InDesign-template_Folder.zip' },
					{ label: 'Pictorials Word Template', url: 'https://dis.acm.org/2025/wp-content/uploads/2024/11/DIS2021-Pictorials-Word-template-Folder.zip' },
					{ label: 'Pictorials Powerpoint Template', url: 'https://dis.acm.org/2025/wp-content/uploads/2024/11/DIS2021-Pictorials-PowerPoint-template-Folder.zip' },
				],
				description: [
					'論文為呈現完整且尚未公開發表之新研究成果的主要媒介；通過審查的論文將被排入研討會發表議程。中英文論文投稿均可，所有投稿需依循 ACM SIGCHI 之雙欄撰寫 paper 格式或採用 DIS 的 pictorial 格式。',
					'論文（Full Paper）',
					'Full Paper 論文投稿格式範本請至 ACM CHI/UIST/DIS 官方網站下載 Sumbission Formats (paper格式)，請作者依照個人偏好的編輯軟體，從下列的連結下載對應的範本檔案：',
					'● [Latex Template](https://portalparts.acm.org/hippo/latex_templates/acmart-primary.zip)',
					'● [Overleaf Template](https://www.overleaf.com/latex/templates/acm-conference-proceedings-primary-article-template/wbvnghjbzwpc)',
					'● [Microsoft Word for Windows](https://www.acm.org/binaries/content/assets/publications/word_style/interim-template-style/interim-layout.docx)',
					'其他資訊請參考 [ACM Template](https://www.acm.org/publications/proceedings-template) 網頁說明。TAICHI 論文頁數**以 8~12 頁為原則但不超過 12 頁**（不含參考文獻），，中文版本字體請使用標楷體，字級則與英文論文相同，均須依循ACM SIGCHI格式規範，請參考範本文件中的內容說明。',
					'圖像式論文（Pictorial）',
					'Pictorial 設計論文格式請參考 [ACM DIS2025](https://dis.acm.org/2025/call-for-pictorials/) 的說明來進行準備 。以下提供範本檔案的連結，請作者依照個人偏好的軟體，下載相對應的檔案來編輯投稿文件：',
					'● [Pictorials InDesign Template](https://dis.acm.org/2025/wp-content/uploads/2024/11/DIS2021-Pictorials-InDesign-template_Folder.zip)',
					'● [Pictorials Word Template](https://dis.acm.org/2025/wp-content/uploads/2024/11/DIS2021-Pictorials-Word-template-Folder.zip)',
					'● [Pictorials Powerpoint Template](https://dis.acm.org/2025/wp-content/uploads/2024/11/DIS2021-Pictorials-PowerPoint-template-Folder.zip)',
					'TAICHI Pictorial 論文頁數**以 8~12 頁為原則但不超過 12 頁**（不含參考文獻）。首頁請按照統一格式排版，若為中文版本字體請使用標楷體，字級則與英文論文相同，均須依循ACM SIGCHI格式規範，請參考範本文件中的內容說明。其他頁則自由排版。',
					'備註',
					'● 所有投稿論文皆採**雙向匿名 (Double-blind)** 審查，請上傳匿名 PDF 檔；若未匿名將直接退稿。PDF 含附件須**小於 20MB**，，請作者用 Acrobat 的最佳化功能，縮減檔案的大小同時確保內容可以清楚地呈現在螢幕上。',
					'● 被錄取論文將收錄於非正式的TAICHI 2026 線上論文集，放置雲端供大家下載閱讀；作者若有投稿疑慮，亦可選擇以摘要形式收錄於非正式的TAICHI 2026線上論文集。',
					'● 論文之後轉投海報的機制會視最終投稿狀況決定，建議以最適合的形式來投稿。',
					'直接退稿規定',
					'● 若投稿論文之主題與研討會徵稿範圍不符、研究貢獻不明確或未完整呈現，或未依規定格式撰寫，主辦單位有權於審查前進行初步篩選並直接退稿（desk reject）。以下為可能之情況說明：',
					'● ● __研究範疇（Scope）__：未能充分回顧相關文獻，或缺乏足夠脈絡以說明研究之新穎性與對設計研究或互動系統領域之貢獻。論文應適當建立於既有研究、設計實務或相關領域之基礎上，且其貢獻應與篇幅相符。',
					'● ● __方法論（Methodology）__：未提供足夠資訊以說明研究方法與過程，包含概念架構不清、論證不完整，或缺乏方法描述與研究透明度。',
					'● ● __資料（Data）__：缺乏足夠資料或證據支持分析與研究主張，致使研究結論難以驗證。',
					'論文主席',
					'Yaliang Chuang / 莊雅量 / 國立清華大學藝術與設計系',
					'Shan Yuan Teng / 鄧善元 / 國立臺灣大學資訊工程學系',
					'Hsin-Ruey (Ray) Tsai / 蔡欣叡 / 國立政治大學資訊科學系',
					'Yu-Chun (Grace) Yen / 顏羽君 / 國立陽明交通大學資訊工程系',
					'論文投稿相關問題請洽 [taiwanchi26+paper@gmail.com](mailto:taiwanchi26+paper@gmail.com)',
				],
			},
			{
				id: 'posters',
				title: '海 報 論 文',
				date: '2026/6/23(二) 23:59 (GMT+8)',
				oldDate: '2026/6/18(四)',
				notificationDate: '2026/7/21(二) 23:59 (GMT+8)',
				cameraReadyDate: '2026/7/27(一) 23:59 (GMT+8)',
				links: [
					{ label: 'Latex', url: 'https://portalparts.acm.org/hippo/latex_templates/acmart-primary.zip' },
					{ label: 'Overleaf', url: 'https://www.overleaf.com/latex/templates/acm-conference-proceedings-primary-article-template/wbvnghjbzwpc' },
					{ label: 'Word', url: 'https://uist.acm.org/2023/assets/files/word-two-column-submission-sample.docx' },
				],
				description: [
					'海報提供作者與研討會參與者直接互動討論正在進行或已在其他研討會發表的研究。受錄取的海報將在研討會海報時段呈現，並且需要至少有一位作者參加研討會並在指定的海報時段進行海報展示。',
					'投稿格式',
					'● 投稿需依循 ACM SIGCHI Publication Format (雙欄) 撰寫，檔案必須為 PDF 檔。',
					'● 投稿格式範本如下：[Latex](https://portalparts.acm.org/hippo/latex_templates/acmart-primary.zip), [Overleaf](https://www.overleaf.com/latex/templates/acm-conference-proceedings-primary-article-template/wbvnghjbzwpc), [Word](https://uist.acm.org/2023/assets/files/word-two-column-submission-sample.docx)',
					'● TAICHI 海報論文頁數**以四頁為原則**（不含參考文獻）。',
					'● 論文內容必須包含摘要、研究動機、目的、方法、目前成果、以及未來研究規劃。',
					'● 海報稿件只需上傳論文，海報檔案將於確定被接受後上傳。',
					'● 所有海報將列入海報論文獎審查，得獎者由會議參與者匿名投票選出。',
					'備註',
					'● 海報投稿採非匿名審查，請在論文中呈現所有必須之作者資訊。請上傳無匿名的 PDF 檔案，如果沒有附上作者資訊，將直接退稿。',
					'● 論文 PDF 檔案含附件須小於 20MB，請作者用 Acrobat 的最佳化功能，縮減檔案的大小同時確保內容可以清楚地呈現在螢幕上。',
					'● 被錄取論文將收錄於非正式的TAICHI 2026 線上論文集，放置雲端供大家下載閱讀；作者若有投稿疑慮，亦可選擇以摘要形式收錄於非正式的TAICHI 2026線上論文集。',
					'● 若投稿論文之主題與研討會徵稿範圍不符、研究貢獻不明確或未完整呈現，或未依規定格式撰寫，主辦單位有權於審查前進行初步篩選並直接退稿（desk reject）。參照Full Paper 與 Pictorial論文規定。',
					'● TAICHI 2026 將與其他國際活動聯合舉辦，鼓勵海報用英文呈現。',
					'海報主席',
					'Chiu-Hsuan Wang / 王秋玄 / 臺大資訊管理系博士後研究員',
					'Fu-Yin Cherng / 程芙茵 / 成大資訊工程系助理教授',
					'Wei-Ming Chung / 莊偉銘 / 銘傳大學商品設計系講師',
					'● 海報論文投稿相關問題請洽 [taiwanchi26+poster@gmail.com](mailto:taiwanchi26+poster@gmail.com)',
				],
			},
			{
				id: 'demos',
				title: '互 動 展 示',
				date: '2026/6/23(二) 23:59 (GMT+8)',
				oldDate: '2026/6/18(四)',
				notificationDate: '2026/7/21(二) 23:59 (GMT+8)',
				cameraReadyDate: '2026/7/27(一) 23:59 (GMT+8)',
				links: [
					{ label: 'Latex', url: 'https://portalparts.acm.org/hippo/latex_templates/acmart-primary.zip' },
					{ label: 'Overleaf', url: 'https://www.overleaf.com/latex/templates/acm-conference-proceedings-primary-article-template/wbvnghjbzwpc' },
					{ label: 'Word', url: 'https://uist.acm.org/2023/assets/files/word-two-column-submission-sample.docx' },
					{ label: '場地需求申請表', url: 'https://docs.google.com/document/d/1uMsKeIa64dYQAFFQLggcIR7leRA1TC7Jc2RsYja3YTY' },
				],
				description: [
					'展示直接於研討會上展現互動概念、手法、裝置或系統的實作成果。受錄取的展示可在展示時段於研討會場中擺設攤位呈現。',
					'投稿格式',
					'● 投稿需依循 ACM SIGCHI Extended Abstract 之格式撰寫。檔案必須為 PDF 檔，不需匿名。標準格式請至 ACM SIGCHI 官方網站下載 CHI Publication Formats。',
					'● 投稿格式範本如下：[Latex](https://portalparts.acm.org/hippo/latex_templates/acmart-primary.zip), [Overleaf](https://www.overleaf.com/latex/templates/acm-conference-proceedings-primary-article-template/wbvnghjbzwpc), [Word](https://uist.acm.org/2023/assets/files/word-two-column-submission-sample.docx)',
					'● 稿件總頁數**上限為三頁**（不含參考文獻），格式採**雙欄排版**。內容可使用中英文撰寫，中文部分請使用標楷體字型。',
					'● 內容必須包含摘要、研究動機、目的、方法、目前成果、以及未來研究規劃。',
					'● 論文標題需以「 Demo: 」為開頭。若同時為 Poster，標題請以「 Poster & Demo: 」為開頭。',
					'● 鼓勵上傳影片以便衡量系統的互動性以及完整程度。上傳影片前請先以 HandBrake 進行壓縮，並輸出成 H.264 之.mp4 檔案。',
					'● 需繳交一份「[場地需求申請表](https://docs.google.com/document/d/1uMsKeIa64dYQAFFQLggcIR7leRA1TC7Jc2RsYja3YTY)」，展示主席將依此協助當天的布展安排。',
					'● 所有系統展示將列入系統展示論文獎審查，得獎者由會議參與者匿名投票選出。',
					'備註',
					'● 被錄取論文將收錄於非正式的TAICHI 2026 線上論文集，放置雲端供大家下載閱讀；作者若有投稿疑慮，亦可選擇以摘要形式收錄於非正式的TAICHI 2026線上論文集。',
					'● 屆時請於會議展示時段前完成攤位佈置。',
					'● TAICHI 2026 將會跟其他國際活動聯合舉辦，鼓勵大家海報用英文呈現。',
					'展示主席',
					'Ching-Wen Hung / 洪靖雯 / 臺大資訊網路與多媒體研究所博士候選人',
					'● 展示投稿相關問題請洽 [taiwanchi26+demo@gmail.com](mailto:taiwanchi26+demo@gmail.com)',
				],
			},
		],
	},
	newsSection: {
		title: 'NEWS',
		subtitle: '最新消息',
		loadMore: '載入更多',
		showLess: '收合',
		readMore: '閱讀更多',
		viewAll: '查看全部消息',
	},
	committeeSection: {
		title: 'Organization',
		subtitle: '委員會成員',
		aboutTitle: 'TAICHI 台灣人機互動學會',
		aboutDescription: [
			'隨著電腦科學的快速發展與進步，電腦融入了人類日常生活的每個層面。人與電腦的溝通手段，人機互動的重要性也日益顯著。由於不同形式的電腦不斷的推陳出新，人機互動的研究不斷的出現新的機會與重要研究議題；其研究成果也常被應用於產業界的服務，與產品緊密結合。在各領域人機互動研究人員的共同努力下，國內人機互動的學術研究在這幾年蓬勃發展，其發表之研究成果也在國際學術領域中佔有一席之地。為了進一步促進台灣的人機互動研究與發展與交流，使其能夠更加繁榮、進步，2016 年春天，在人機互動產學界先進們的關注與支持之下，台灣人機互動學會於國立台灣大學資訊工程學系成立，並在同年夏初獲准設立。',
		],
		aboutButtonText: '學會網站',
		aboutButtonUrl: 'https://taiwanchi.org/',
		chairTitles: {
			'general chairs': { zh: '會議主席', en: 'GENERAL CHAIRS' },
			'steering committees': { zh: '指導委員', en: 'STEERING COMMITTEES' },
			'program chairs': { zh: '議程主席', en: 'PROGRAM CHAIRS' },
			'paper chairs': { zh: '論文主席', en: 'PAPER CHAIRS' },
			'poster chairs': { zh: '海報主席', en: 'POSTER CHAIRS' },
			'demo chairs': { zh: '展示主席', en: 'DEMO CHAIRS' },
			'panel chairs': { zh: '論壇主席', en: 'PANEL CHAIRS' },
			'workshop chairs': { zh: '工作坊主席', en: 'WORKSHOP CHAIRS' },
			'publicity chairs': { zh: '宣傳主席', en: 'PUBLICITY CHAIRS' },
			'performance chairs': { zh: '表演主席', en: 'PERFORMANCE CHAIRS' },
			'beer chairs': { zh: '酒吧主席', en: 'BEER CHAIRS' },
			'family chairs': { zh: '家庭主席', en: 'FAMILY CHAIRS' },
			'sponsor chairs': { zh: '贊助主席', en: 'SPONSOR CHAIRS' },
			'publication chairs': { zh: '出版主席', en: 'PUBLICATION CHAIRS' },
			'design competition chairs': { zh: '競賽主席', en: 'COMPETITION CHAIR' },
			'best paper award committee': { zh: '論文獎委員', en: 'BEST PAPER AWARD COMMITTEE' },
			'web chairs': { zh: '網路主席', en: 'WEB CHAIRS' },
			'visual chairs': { zh: '視覺主席', en: 'VISUAL CHAIRS' },
			'registration chairs': { zh: '註冊主席', en: 'REGISTRATION CHAIRS' },
			'student volunteer chairs': { zh: '學生志願主席', en: 'STUDENT VOLUNTEER CHAIRS' },
		},
	},
	competitionSection: {
		title: 'Competition',
		badge: 'COMING SOON',
		highlightTitle: '精彩競賽即將登場',
		description: 'TAICHI 2026 正在籌備精彩的競賽活動，敬請期待！相關資訊將於近期公佈，請密切關注官網更新。',
	},
	familyFriendlySection: {
		title: 'Family-Friendly',
		seoTitle: 'Family-Friendly',
		seoDescription: 'TAICHI 2026 歡迎攜帶家屬同行，打造更友善的參與現場。',
		headline: 'TAICHI 2026 歡迎家屬同行',
		paragraphs: [
			'TAICHI 2026 歡迎與會者，也歡迎您的家人一同前來。',
			'家人是我們的力量，也是我們靈感的來源。伴侶、孩子、父母，陪伴我們走在研究與生活的路上。邀請他們同行，對我們而言再自然不過。',
			'今年，TAICHI 2026 首度推出家庭友善規劃，希望讓有家屬同行的與會者能更安心參與會議。我們將設置家庭友善空間，提供休息、陪伴與簡單遊戲的角落；也會為對「爸爸媽媽／家人平常在忙什麼」感到好奇的孩子，準備輕鬆的小活動。此外，會議廳內也將保留家庭友善座位，讓有照顧需求的與會者能更彈性地參與議程。',
			'我們也將提供一份簡短的會場周邊家庭友善指南，協助您找到附近的公園、藥局、便利設施，以及適合短暫休息的安靜角落。',
			'這是 TAICHI 首次嘗試推動家庭友善會議安排。我們期待透過這項創舉，讓學術社群更貼近真實的生活，也讓更多研究者能在被支持的狀態下參與交流。若您計畫攜帶家屬前來，請在報名表中告訴我們，以便我們提前準備。',
			'期待在 TAICHI 2026 與您和您的家人相見。',
		],
		surveyHeading: 'TAICHI 2026 家屬同行意願調查',
		surveyDescription: '若您計畫攜帶家屬前來，請填寫此調查表，協助我們提前準備。',
		surveyButtonText: '前往調查表',
		surveyUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSe00DvkS2zWTNY0Hfi0mKwePdPc-777Jypcxh1ulxQ7DRDcJg/viewform',
		outroLine: '更多活動規劃將後續公告！敬請期待！',
	},
	sponsorshipSection: {
		seoTitle: '贊助邀請',
		seoDescription: 'TAICHI 2026 誠摯邀請企業機關共同襄助第十二屆臺灣人機互動研討會，下載完整贊助邀請與辦法。',
		pageTitle: 'Sponsorship',
		kicker: 'TAICHI 2026 SPONSORSHIP',
		headline: '一起把未來 Big Bang！',
		paragraphs: [
			'TAICHI 2026 將在 8/5–8/6 於臺北三創生活園區與臺北科技大學登場。本屆主題「Big Bang! Futures」把宇宙大霹靂的瞬間帶進城市——這裡是一個可以逛、可以玩、可以一起參與的未來現場，透過互動裝置、實驗作品與夜市般的體驗空間，讓大家親身感受科技如何形塑未來的生活。',
			'今年特別不一樣：8/5 我們在三創與國科會臺灣晶創人文計畫、亞太區 APMAR、科技藝術學會 ISAT 串聯，把學術、展演與公眾參與聚在同一個場域，預期吸引大量學者、業界夥伴與民眾一同參與。',
			'TAICHI 是臺灣人機互動社群每年最重要的聚會，自 2015 年起持續舉辦，每年匯聚上百位國內外學者、產業夥伴與學生；社群成員的研究也常亮相於 CHI、UIST、CSCW、Ubicomp、DIS 等頂尖國際會議。',
			'誠摯邀請您成為今年的贊助夥伴，讓您的品牌與這群最具創造力的人相遇，一起把臺灣的未來體驗 Big Bang！以下整理了各項贊助方案，期待與您攜手同行。',
		],
		highlightsTitle: '活動重點',
		highlights: [
			{ label: 'DATE 日期', value: '2026 / 8 / 5 – 8 / 6' },
			{ label: 'VENUE 地點', value: '臺北三創生活園區 × 臺北科技大學' },
			{ label: 'THEME 主題', value: 'Big Bang! Futures' },
			{ label: 'CO-HOSTED 串聯', value: '晶創人文計畫 × APMAR × ISAT' },
			{ label: 'COMMUNITY 社群', value: '每年上百名學者・業界・學生參與' },
		],
		plansTitle: '贊助方案',
		plansIntro: '大會目前提供以下贊助方案，若方案不符貴機構需求，也歡迎聯絡大會洽談其他贊助方案。',
		tierNames: ['鑽石級', '白金級', '金級', '銀級'],
		planRows: [
			{ label: '金額 (NT$)', values: ['80,000', '50,000', '30,000', '15,000'] },
			{ label: '研討會贈票名額', values: ['8', '6', '3', '2'] },
			{ label: '大會網站 Logo 宣傳', values: ['✓', '✓', '✓', '✓'] },
			{
				label: '大會現場 Logo 宣傳',
				values: ['舞台、講台、報到與會場等布置露出', '舞台、講台、報到與會場等布置露出', '舞台、講台、報到與會場等布置露出', '舞台、講台、報到與會場等布置露出'],
			},
			{ label: '線上手冊（議程）Logo 宣傳', values: ['Logo 顯示／宣傳文案', 'Logo 顯示／宣傳文案', 'Logo 顯示／宣傳文案', 'Logo 顯示'] },
			{ label: '專屬參展攤位', values: ['一組兩格', '一組一格', '一組一格', '—'] },
			{ label: '宣傳品放置報到桌', values: ['✓', '✓', '✓', '—'] },
			{ label: '大會現場影片輪播', values: ['✓（30 sec）', '✓（10 sec）', '✓（5 sec）', '—'] },
			{ label: '8/5 互動夜市會場', values: ['Logo 露出／上台介紹（8 min）', 'Logo 露出／上台介紹（5 min）', 'Logo 露出', '—'] },
		],
		plansNoteTitle: '聯繫與注意事項',
		plansNotes: [
			'填寫贊助同意書前，請先與大會籌備處聯絡，確認各項贊助項目。',
			'請於確認贊助項目後一週內完成匯款程序，以利大會宣傳作業進行。',
			'以上贊助方案名額、空間有限，大會將依繳費先後順序保留相關決定權。',
		],
		pdfHeading: '完整贊助邀請與辦法',
		pdfDescription: '各贊助方案、權益與報名方式詳見完整辦法文件，歡迎下載參閱。',
		pdfButtonText: '下載贊助邀請與辦法 (PDF)',
		pdfUrl: '/docs/2026-TAICHI贊助邀請與辦法.pdf',
		processTitle: '贊助流程',
		processSteps: [
			{
				title: '步驟 1 ｜ 確認各項贊助項目',
				body: [
					'贊助聯絡人：銘傳大學資訊管理學系 陳書儀（Max Chen）｜0952-702363｜maxchen@mail.mcu.edu.tw',
					'匯款問題聯絡人：臺灣人機互動學會會務 賴紫晴｜02-33664888 轉 503｜june@cmlab.csie.ntu.edu.tw',
				],
			},
			{
				title: '步驟 2 ｜ 寄送廠商贊助同意書',
				body: ['Email 或傳真【廠商贊助同意書】至賴紫晴（june@cmlab.csie.ntu.edu.tw）及陳書儀（maxchen@mail.mcu.edu.tw）。'],
			},
			{
				title: '步驟 3 ｜ 匯款',
				body: ['戶名：社團法人臺灣人機互動學會', '銀行：華南商業銀行（銀行代號 008）', '帳號：154-10-009173-1'],
			},
			{
				title: '步驟 4 ｜ 匯款通知',
				body: [
					'匯款後請 Email 至賴紫晴（june@cmlab.csie.ntu.edu.tw）及陳書儀（maxchen@mail.mcu.edu.tw），並註明：',
					'1. 匯款帳戶後五碼',
					'2. 匯款公司聯絡人的姓名與電話',
				],
			},
		],
		contactHeading: '贊助洽詢',
		contactText: '有任何贊助相關問題，歡迎來信與籌備團隊聯繫：',
		contactEmail: 'maxchen@mail.mcu.edu.tw',
	},
	keynoteSection: {
		title: 'KEYNOTE SPEAKERS',
		subtitle: '專題演講',
		tbd: '講者即將公布',
	},
	programSection: {
		title: 'AGENDA',
		subtitle: '會議時程',
		viewDetail: '場次 // ',
		backToIndex: '返回議程',
		viewProject: '場次 // ',
		agendaTba: '議程即將公布。',
		chairsLabel: '主席',
	},
	programPageSection: {
		title: 'PROGRAM',
		dateTabs: [
			{ key: 'day1', date: '8.05', day: 'WED' },
			{ key: 'day2', date: '8.06', day: 'THU' },
		],
		heroCaption: '晶創人文, TAICHI, APMAR, ISAT 聯合活動',
		heroDescription: 'Big Bang! Futures! 由晶創人文、TAICHI、APMAR 與 ISAT 聯合策劃，匯聚科技、人文、藝術與設計，共同解鎖未來的多重可能。',
		labels: {
			scheduleTitle: '完整時程表',
			photoPlaceholder: '照片',
			timeLocationLabel: '時間/地點',
		},
		day1: {
			sessions: [
				{
					id: 'day1-5f',
					title: 'Big Bang! 調頻未來',
					tagline: '每一個聲音，都是一種未來',
					time: '09:20 - 16:40',
					location: '臺北三創生活園區 5F展演廳',
					tags: ['Keynotes', 'Panels', 'International Exchange'],
					description: '從主題演講、論壇對談到研究分享，不同領域的觀點在此交會。傾聽、交流、思考，解鎖更多未來的可能。',
					gradient: true,
					schedule: [
						{ time: '9:20 - 9:45', label: '報到' },
						{ time: '9:45 - 10:00', label: '開幕' },
						// TODO: 完整簡歷待補
						{ time: '10:00 - 11:00', label: 'Jun Rekimoto', sublabel: '東京大學名譽教授、Sony CSL 京都實驗室總監', featured: true, fullBio: '完整簡歷尚未提供，敬請期待。' },
						// TODO: 完整簡歷待補
						{ time: '11:05 - 12:05', label: 'Pedro Lopes', sublabel: '芝加哥大學電腦科學副教授', featured: true, fullBio: '完整簡歷尚未提供，敬請期待。' },
						{ time: '12:05 - 13:30', label: '午餐時間' },
						// TODO: 完整簡歷待補
						{ time: '13:30 - 14:30', label: 'Huaishu Peng', sublabel: '馬里蘭大學電腦科學副教授', featured: true, fullBio: '完整簡歷尚未提供，敬請期待。' },
						{
							time: '10:00 - 11:00' /* TODO: 確認正確時間，與 Jun Rekimoto 場次重複 */,
							label: 'Andrea Bianchi',
							sublabel: '韓國科學技術院（KAIST）工業設計系副教授、計算科學系兼任教授',
							featured: true,
							fullBio:
								'Andrea Bianchi 是韓國科學技術院（KAIST）工業設計系副教授、計算科學系兼任教授，同時也是 Make Lab 的主持人。他的研究領域為人機互動（HCI），專注於開發互動系統原型工具及混合實境（MR）中的擴增身體硬體設備。在加入 KAIST 前，他曾任教於韓國成均館大學計算機科學系，並曾於紐約一家新創公司擔任電子遊戲程式設計師。Andrea 的研究成果曾發表於 ACM CHI、UIST 和 IMWUT 等頂尖國際會議，屢獲最佳論文獎與設計獎項，並廣受 Engadget、ZDNet、New Scientist、MAKE 及 Gizmodo 等媒體報導。Andrea 於 2012 年取得 KAIST 博士學位，並於 2007 年獲得紐約大學碩士學位。',
						},
						{ time: '15:35 - 15:40', label: '午茶時間' },
						{ time: '10:00 - 11:00' /* TODO: 確認正確時間，與 Jun Rekimoto 場次重複 */, label: '論壇', sublabel: 'Jun Rekimoto, Huaishu Peng, Andrea Bianchi', featured: true },
					],
				},
				{
					id: 'day1-12f',
					title: 'Big Bang! 互動夜市',
					tagline: '今晚，逛的不只是夜市',
					time: '15:30 - 20:00',
					location: '臺北三創生活園區 12F多元廳',
					tags: ['Demo', 'Poster', 'Performances', 'Food', 'Market'],
					description: '這裡不只是夜市，更是科技、人文與創意交會的現場。探索於互動展示、研究海報、Live Coding、布袋戲投影演出，以及限定夜市美食之間，解鎖屬於你的多元宇宙。',
					gradient: false,
					schedule: [
						{ time: '13:30', label: '開放' },
						{ time: '17:30', label: '開幕與介紹' },
						{ time: '17:45', label: 'ISAT若水獎頒獎' },
						// TODO: 完整簡歷待補
						{
							time: '18:00',
							label: '國立陽明交通大學｜體驗設計實驗室',
							sublabel: '《未來布袋戲：幻相・乾坤》混合實境 × 當代舞蹈沉浸式演出',
							featured: true,
							fullBio: '完整簡歷尚未提供，敬請期待。',
						},
						{
							time: '18:10',
							label: '何樵暐',
							sublabel: '《unix_time》',
							featured: true,
							fullBio:
								'何樵暐工作室Hochiaowei Practices是一個獨立運作的創作集合：其中DML（Digital Medicine Lab）聚焦於推測設計與新媒體的創作與研究；TPS Press（tshut-pán-siā）透過獨立出版推廣具文化批判性與實驗精神的設計書籍；聲音計畫 KIKORI Collective 藉由即時編碼及社群TOPLAP NTUST，使聲音成為能被自由運用的創作媒材；教學實驗 SNN（School of New Now）專注於教授開源導向的創作工具與方法，讓知識能被平等共享。',
							workHeading: '開幕表演：《unix_time》',
							workDescription:
								'《unix_time》是一首以即時編碼生成的電子聲音作品。作品以數字、倒數、警示聲與系統提示音作為主要素材，將一串原本沒有特定意涵的數字，在現場組織成持續逼近終點的聲音結構。\n\n抽象的數字本身並不攜帶事件。數字只是被排列的符號；但當它們開始以倒數的形式運行，這串符號便產生了一種指向性。這件作品並不試圖讓倒數成為任何特定「象徵」，而是把倒數視為一種空的結構。當數字逐漸逼近終點，真正被聽見的不是某個明確事件，而是我們如何把想像中的未來安裝進一串數字之中。',
						},
						{ time: '20:00', label: '自由結束' },
					],
				},
			],
			performance: {
				title: '表演區介紹',
				cards: [
					{
						name: 'Vibe Coding 舞台',
						description: '不是 DJ，也不是傳統演出，而是把程式碼搬上舞台。創作者透過 AI 與 Live Coding 即時編寫程式，讓聲音、影像與互動在觀眾面前同步誕生。每一次演出都無法重現，每一場都是一場只存在當下的 Big Bang。',
					},
					{
						name: 'TOPLAP NTUST',
						description: 'TOPLAP NTUST 是一個以 Live Coding（即時編碼）為核心，結合即時影像與現場表演的電子音樂組織。延續國際 TOPLAP 與 Algorave 的精神，透過即時生成的聲音與影像，讓 Live Coding 成為一種持續演變的音樂文化與生活風格。',
						toggleLabel: '表演順序',
						// TODO: 實際表演順序待補
						toggleContent: '表演順序尚未公布，敬請期待。',
					},
				],
				// TODO: 語序疑似錯亂，待確認正確文案（讀起來應為「表演區結尾，歡迎現場觀眾自由登台，一起加入 Live Coding！」）
				closingLine1: '歡表演區結尾迎現場觀眾自由登台，',
				closingLine2: '一起加入 Live Coding！',
			},
			residency: {
				title: '紙箱椅作品介紹',
				introTitle: '這裡不只是張休息椅',
				introInstructor: '指導老師：設計系鄭宇婷 助理教授',
				introDescription: '紙箱椅是國立臺灣科技大學設計系一年級《基本設計》課程的重要成果。學生僅能使用一張 100 × 200 公分的瓦楞紙板，不使用膠水或任何其他材料，僅透過切割、摺疊與卡榫結構完成一張可承重的椅子。展出的作品從課程成果中精選，化身為 Big Bang! Futures 休息區的公共座椅，讓設計從課堂走入展場，也邀請每位觀眾親身體驗設計的創意與可能。',
				cards: [
					{
						name: '米凳子',
						description: '《米凳子》因側面神似「米」字而得名。透過圓潤的線條與紙板堆疊工法，在有限的材料中兼顧美感與支撐力，讓簡單的紙板，也能化身舒適、紮實又可愛的凳子。',
						toggleLabel: '設計師簡介',
						// TODO: 設計師簡介待補
						toggleContent: '設計師簡介尚未提供，敬請期待。',
					},
					{
						name: 'ㄇ椅',
						description: '椅子本身由四片ㄇ字型的紙板組裝而成，故取名為ㄇ椅，同時承載了台灣獨有的注音文化，發想時希望能最大程度利用紙板紋路縱向的承重，同時最低程度的破壞紙板的完整性，兩者同時達成就能保有很高的支撐力，並且有簡約質感的風格呈現，於是僅由四片結構就能組裝完成的ㄇ椅就誕生了。',
						toggleLabel: '設計師簡介',
						// TODO: 設計師簡介待補
						toggleContent: '設計師簡介尚未提供，敬請期待。',
					},
				],
			},
			food: {
				title: 'Food 介紹',
				cards: [
					{
						name: 'CANCAN',
						// TODO: CANCAN 真實文案待補（Figma 原稿此處為複製貼上的占位文字，與此攤位無關，故不沿用）
						description: '',
					},
					{
						name: '老濟安 Healing Herbar',
						description: '創立於 1972 年的老濟安，傳承萬華青草巷三代草本文化，持續以創新風味詮釋臺灣青草茶。此次與 Big Bang! Futures 聯名合作，透過限定草本特調，讓在地傳統與未來想像交融。',
						longform: true,
					},
				],
				promo: {
					heading: '限量聯名飲品',
					items: ['待老濟安命名 [酒精]', 'Big Bang! 老濟安青草茶聯名款[無酒精]'],
				},
			},
		},
		day2: {
			sessions: [
				{ id: 'day2-taichi', title: 'TAICHI年度學會', time: '08:00 - 17:00', location: '國立臺北科技大學宏裕科技大樓 B1國際會議廳' },
				{ id: 'day2-isat', title: 'ISAT年度學會', time: '08:00 - 17:00', location: '國立臺北科技大學光華館 多功能展演廳' },
			],
		},
	},
	venueSection: {
		title: 'Venue',
		subtitle: '活動行程',
		submenuItems: [
			{ label: 'Overview', target: 'venue-overview' },
			{ label: '8/5', target: 'venue-day-1' },
			{ label: '8/6', target: 'venue-day-2' },
		],
		dayButtons: [{ label: '[ 8/5 ]', target: 'venue-day-1' }, { label: '[ 8/6 ]', target: 'venue-day-2' }],
		openMap: '開啟地圖',
		topButton: 'TOP',
		overview: {
			title: 'Overview',
			intro:
				'本屆 TAICHI 為一系列跨域大型活動的一部分（2026/08/03–08/06），與臺灣晶創人文計畫、國際亞洲區 APMAR、以及科技藝術學會 ISAT 共同串聯，打造橫跨學術、展演與公共參與的整體場域。8/3 至 8/4 由 APMAR 率先展開活動，8/5 四個單位共同對外開放，進行國際 keynote、互動市集與表演，8/6 則進入 TAICHI 研討會議程。',
			events: {
				preEvent: {
					date: '2026/08/03–04 [APMAR]',
					description: [
						'APMAR 將於 8/3 與 8/4 率先展開，以藝術研究、跨域實作與國際交流為核心，串接本屆 TAICHI 系列活動的前導內容。',
						'這裡可查看 APMAR 活動資訊與官網，了解完整議程與主辦內容。',
					],
					buttonLabel: '進入 APMAR 活動網站',
					buttonType: 'external',
					href: 'https://sites.google.com/view/apmar2026/',
					image: '/images/overview-02.jpg',
				},
				day1: {
					date: '2026/08/05 [TAICHI × 晶創人文 × APMAR × ISAT]',
					description: [
						'8/5 將於三創生活園區舉辦四單位聯合開放日，包含國際 keynote、互動夜市、展演與公眾參與活動。',
						'點擊下方按鈕可直接前往 8/5 的場地與活動資訊。',
					],
					buttonLabel: '查看 8/5 場地資訊',
					buttonType: 'section',
					target: 'venue-day-1',
					image: '/images/overview-03.jpg',
				},
				day2: {
					date: '2026/08/06 [TAICHI]',
					description: [
						'8/6 於國立臺北科技大學進行 TAICHI 年度研討會，聚焦論文發表、論壇與學術交流。',
						'點擊下方按鈕可直接前往 8/6 的場地與活動資訊。',
					],
					buttonLabel: '查看 8/6 場地資訊',
					buttonType: 'section',
					target: 'venue-day-2',
					image: '/images/overview-04.jpg',
				},
			},
			timeline: [
				{ label: '8/3', sublabel: 'APMAR', key: 'preEvent' },
				{ label: '8/4', sublabel: 'APMAR', key: 'preEvent' },
				{ label: '8/5', sublabel: 'TAICHI, 晶創人文 / APMAR, ISAT', key: 'day1' },
				{ label: '8/6', sublabel: 'TAICHI', key: 'day2' },
			],
		},
		days: [
			{
				id: 'venue-day-1',
				tabLabel: '[ 8/5 ]',
				heroImage: '/images/day1location.avif',
				heroTitle: '8/5(三) 互動夜市 [對外公開]',
				heroSubtitle: 'TAICHI、晶創人文、APMAR、ISAT 聯合活動',
				highlight: { label: '地點', venue: '臺北三創生活園區 5F 和 12F', details: ['5F 國際大咖 Keynote 演講連環場', '12F 互動夜市、小吃、表演揍作伙來'], note: '詳細行程表待公告。' },
				venues: [
					{ title: '5F 展演廳 [三創生活園區]', subtitle: 'Syntrend Creative Park, Taipei', addressLabel: '地址', addressZh: '100013 臺北市中正區市民大道三段 2 號', addressEn: 'No. 2, Sec. 3, Civic Blvd., Zhongzheng Dist., Taipei City 100013', venueLabel: '會議場地', venueName: '5F 廳提供 keynote 與論壇，滿滿大咖國際演講。', photoImage: '/images/day1_5F.jpg', mapLink: 'https://maps.app.goo.gl/yYLTdcVH5rSMevEF8', mapEmbedSrc: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3614.6633085538724!2d121.52874377537685!3d25.04549777780891!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3442a97b582d5a73%3A0x9b1e56ab48807d62!2z5LiJ5Ym155Sf5rS75ZyS5Y2A!5e0!3m2!1szh-TW!2stw!4v1772020903779!5m2!1szh-TW!2stw' },
					{ title: '12F 多元廳 [三創生活園區]', subtitle: 'Syntrend Creative Park, Taipei', addressLabel: '地址', addressZh: '100013 臺北市中正區市民大道三段 2 號', addressEn: 'No. 2, Sec. 3, Civic Blvd., Zhongzheng Dist., Taipei City 100013', venueLabel: '會議場地', venueName: '互動夜市、小吃、表演。', photoImage: '/images/day1_12F.jpg', mapLink: 'https://maps.app.goo.gl/yYLTdcVH5rSMevEF8', mapEmbedSrc: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3614.6633085538724!2d121.52874377537685!3d25.04549777780891!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3442a97b582d5a73%3A0x9b1e56ab48807d62!2z5LiJ5Ym155Sf5rS75ZyS5Y2A!5e0!3m2!1szh-TW!2stw!4v1772020903779!5m2!1szh-TW!2stw' },
				],
				travelPanels: [
					{ title: '大眾運輸', items: [{ title: '捷運 MRT', lines: ['板南線 / 忠孝新生站 1 號出口，步行約 3 分鐘', '新蘆線 / 忠孝新生站 1 號出口，步行約 3 分鐘'] }, { title: '公車 Bus', lines: ['三創生活園區、光華商場周邊站牌，多條路線可達'] }] },
					{ title: '自行開車', items: [{ title: '停車資訊', lines: ['三創生活園區停車場', '光華數位新天地周邊停車場', '建國高架橋下停車場'] }], calloutTitle: '建議', callout: '活動時段人潮較多，建議優先搭乘大眾運輸工具。' },
				],
			},
			{
				id: 'venue-day-2',
				tabLabel: '[ 8/6 ]',
				heroImage: '/images/day2location.avif',
				heroTitle: '8/6(四) 年度研討會',
				heroSubtitle: 'TAICHI 年度學會研討會',
				highlight: { label: '地點', venue: '國立臺北科技大學 科研大樓', details: ['論文發表與論壇講座'], note: '詳細議程與場地配置將陸續公告。' },
				venues: [
					{ title: '國際會議廳 [國立臺北科技大學 科研大樓]', subtitle: 'National Taipei University of Technology, Taipei', addressLabel: '地址', addressZh: '10608 臺北市大安區忠孝東路三段 1 號', addressEn: "No. 1, Sec. 3, Zhongxiao E. Rd., Da'an Dist., Taipei City 10608", venueLabel: '會議場地', venueName: '論文發表、講座。', photoImage: '/images/day2_X.avif', mapLink: 'https://maps.app.goo.gl/p97U3oZnXoUvrXmo7', mapEmbedSrc: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d903.6783181717664!2d121.53284755506823!3d25.043802836933057!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3442a97d255598df%3A0x47ea748e8f3f53aa!2z5ZyL56uL6Ie65YyX56eR5oqA5aSn5a24!5e0!3m2!1szh-TW!2stw!4v1772020528494!5m2!1szh-TW!2stw' },
				],
				travelPanels: [
					{ title: '大眾運輸', items: [{ title: '捷運 MRT', lines: ['板南線 / 忠孝新生站 4 號出口，步行約 5 分鐘', '文湖線 / 忠孝復興站轉乘，步行或公車前往'] }, { title: '高鐵 HSR / 台鐵 TRA', lines: ['台北車站下車後轉乘捷運板南線至忠孝新生站'] }, { title: '公車 Bus', lines: ['正義郵局、臺北科技大學周邊站牌，多條路線可達'] }] },
					{ title: '自行開車', items: [{ title: '停車資訊', lines: ['北科大周邊停車場', '建國高架橋下停車場', '臺北科技大學周邊收費停車格'] }], calloutTitle: '建議', callout: '校園周邊停車位有限，建議提前抵達或改搭捷運前往。' },
				],
			},
		],
	},
	sponsorsSection: {
		mainOrganizers: '主辦單位',
		coOrganizersTitle: '共同主辦',
		organizers: [
			{ name: '台灣人機互動學會', logo: '/logos/taichi.webp', size: 'large', className: 'px-8 py-5 rounded-3xl shadow-2xl' },
			{ name: '國科會晶創人文計畫', logo: '/logos/NSTC.png', size: 'large', className: 'px-8 py-5 rounded-3xl shadow-2xl' },
		],
		coOrganizers: [
			{ name: '國立臺灣科技大學', logo: '/logos/NTUST.png', size: 'small', className: 'px-6 py-4 rounded-2xl shadow-xl' },
			{ name: '國立臺北科技大學', logo: '/logos/NTUT.png', size: 'S', className: 'px-6 py-4 rounded-2xl shadow-xl' },
		],
		supportingOrganizersTitle: '協辦單位',
		supportingOrganizers: [
			{ name: '台灣科技藝術學會', logo: '/logos/ISAT.png', size: 'small', className: 'px-6 py-4 rounded-2xl shadow-xl' },
			{ name: 'APMAR', logo: '/logos/APMAR.png', size: 'small', className: 'px-6 py-4 rounded-2xl shadow-xl' },
		],
		sponsorsTitle: '贊助單位',
		sponsors: [
			{ name: '美國在台協會', logo: '/logos/AIT.png', size: 'large', className: 'px-6 py-4 rounded-2xl shadow-xl' },
			{ name: '美國創新中心', logo: '/logos/AIC.png', size: 'large', className: 'px-6 py-4 rounded-2xl shadow-xl' },
			{ name: '國科會工程科技推展中心', logo: '/logos/ETPC.png', size: 'large', className: 'px-6 py-4 rounded-2xl shadow-xl' },
		],
	},
	footer: {
		title: 'TAICHI 2026 \n BIG BANG! FUTURE!',
		socialsTitle: 'FOLLOW US',
		facebook: 'https://www.facebook.com/taiwanchi',
		locationsTitle: 'CONTACT',
		locationsList: ['taiwanchi26@gmail.com', 'Taipei, Taiwan'],
		copyright: 'COPYRIGHT © 2026 TAICHI',
		credits: '',
	},
	contact: CONFIG.contact,
} as const;
