// AUTO-GENERATED by scripts/freeze-notion-data.mjs on 2026-08-10T08:11:16.634Z
// 活動結束後自 Notion 凍結的資料快照，請勿手動編輯；需更新時重跑：
//   node scripts/freeze-notion-data.mjs
// Source DBs — people: 2e7ceff5447080aebbbbf20d0ee07a0b / sessions: af10738ec6964a58ba15b4f10219ad99 / topics: 2e7ceff544708077a369df3f0643c99e / news: 2e8ceff5447080c7914bfdbcb9758808
// 詳見 HANDOVER.md

export const FROZEN_PEOPLE: PersonItem[] = [
	{
		"id": "36eceff5-4470-813d-b4dc-fe2649b6ef84",
		"name": "Gary Hsieh",
		"nameEn": "Gary Hsieh",
		"chairType": "Best Paper Award Committee",
		"image": "/images/people/gary_hsieh.jpg",
		"institution": "University of Washington",
		"institutionEn": "University of Washington",
		"department": "Professor, Human Centered Design & Engineering (HCDE)",
		"departmentEn": "Professor, Human Centered Design & Engineering (HCDE)",
		"order": 5
	},
	{
		"id": "36eceff5-4470-81e3-8e10-d25219a2a5ce",
		"name": "Lin-Lin Chen",
		"nameEn": "Lin-Lin Chen",
		"chairType": "Best Paper Award Committee",
		"image": "/images/people/lin_lin_chen.jpg",
		"institution": "Eindhoven University of Technology",
		"institutionEn": "Eindhoven University of Technology",
		"department": "Dean, Industrial Design",
		"departmentEn": "Dean, Industrial Design",
		"order": 4
	},
	{
		"id": "36eceff5-4470-8182-b525-fce2591c2d8c",
		"name": "Ellen Yi-Luen Do",
		"nameEn": "Ellen Yi-Luen Do",
		"chairType": "Best Paper Award Committee",
		"image": "/images/people/ellen_yi_luen_do.jpg",
		"institution": "University of Colorado Boulder",
		"institutionEn": "University of Colorado Boulder",
		"department": "Professor, ATLAS Institute & Computer Science",
		"departmentEn": "Professor, ATLAS Institute & Computer Science",
		"order": 3
	},
	{
		"id": "36eceff5-4470-81ce-9ace-ca7bed85a11a",
		"name": "Kwan-Liu Ma",
		"nameEn": "Kwan-Liu Ma",
		"chairType": "Best Paper Award Committee",
		"image": "/images/people/kwan_liu_ma.jpg",
		"institution": "University of California, Davis",
		"institutionEn": "University of California, Davis",
		"department": "Distinguished Professor, Computer Science",
		"departmentEn": "Distinguished Professor, Computer Science",
		"order": 2
	},
	{
		"id": "36eceff5-4470-8100-938f-c6f9b85a6d90",
		"name": "Ed H. Chi",
		"nameEn": "Ed H. Chi",
		"chairType": "Best Paper Award Committee",
		"image": "/images/people/ed_h_chi.png",
		"institution": "Google DeepMind",
		"institutionEn": "Google DeepMind",
		"department": "VP of Research",
		"departmentEn": "VP of Research",
		"order": 1
	},
	{
		"id": "312ceff5-4470-8028-86dc-e3c4f50f3942",
		"name": "陳奕安",
		"chairType": "Visual Chairs",
		"image": "/images/people/person_f50f3942.jpg",
		"institution": "國立臺灣科技大學",
		"institutionEn": "National Taiwan University of Science and Technology",
		"department": "設計系",
		"departmentEn": "Department of Design",
		"notes": "碩士生",
		"order": 1
	},
	{
		"id": "312ceff5-4470-80f8-b523-db133561b7fe",
		"name": "陳書廷",
		"chairType": "Visual Chairs",
		"image": "/images/people/_placeholder_person.jpg",
		"institution": "國立臺灣科技大學",
		"institutionEn": "National Taiwan University of Science and Technology",
		"department": "設計系",
		"departmentEn": "Department of Design",
		"notes": "碩士生",
		"order": 0
	},
	{
		"id": "312ceff5-4470-80ac-b8de-f31437a51426",
		"name": "游創文",
		"nameEn": "Chuang-Wen You",
		"chairType": "Family Chairs",
		"image": "/images/people/chuang_wen_you.jpg",
		"institution": "國立清華大學",
		"institutionEn": "National Tsing Hua University",
		"department": "科技藝術所",
		"departmentEn": "Graduate Institute of Art and Technology",
		"notes": "副教授",
		"order": 2
	},
	{
		"id": "311ceff5-4470-8198-9cb6-de45c11cf25b",
		"name": "陳怡瑾",
		"nameEn": "I-Chin Chen",
		"chairType": "Student Volunteer Chairs",
		"image": "/images/people/_placeholder_person.jpg",
		"institution": "國立陽明交通大學",
		"institutionEn": "National Yang Ming Chiao Tung University",
		"department": "應用藝術研究所",
		"departmentEn": "Institute of Applied Arts",
		"notes": "碩士生",
		"order": 0
	},
	{
		"id": "311ceff5-4470-81d4-8f23-e2aa9a55ffa9",
		"name": "顏維廷",
		"nameEn": "Wei-Ting Yen",
		"chairType": "Student Volunteer Chairs",
		"image": "/images/people/_placeholder_person.jpg",
		"institution": "國立臺灣科技大學",
		"institutionEn": "National Taiwan University of Science and Technology",
		"department": "人工智慧跨域科技研究所",
		"departmentEn": "Graduate Institute of A.I. Cross-disciplinary Technology",
		"notes": "碩士生",
		"order": 1
	},
	{
		"id": "311ceff5-4470-813d-b3bb-e07e41f8e116",
		"name": "施孟廷",
		"nameEn": "Meng-Ting Shih",
		"chairType": "Registration Chairs",
		"image": "/images/people/_placeholder_person.jpg",
		"institution": "國立陽明交通大學",
		"institutionEn": "National Yang Ming Chiao Tung University",
		"department": "資訊工程系",
		"departmentEn": "Department of Computer Science",
		"notes": "博士生",
		"order": 0
	},
	{
		"id": "311ceff5-4470-81b0-bb8a-c1dedc1d7f62",
		"name": "羅子程",
		"nameEn": "Tzu-Cheng Lo",
		"chairType": "Web Chairs",
		"image": "/images/people/_placeholder_person.jpg",
		"institution": "國立臺灣科技大學",
		"institutionEn": "National Taiwan University of Science and Technology",
		"department": "人工智慧跨域科技研究所",
		"departmentEn": "Graduate Institute of A.I. Cross-disciplinary Technology",
		"notes": "碩士生",
		"order": 0
	},
	{
		"id": "311ceff5-4470-8170-8f71-c456c66da4a0",
		"name": "陳書儀",
		"nameEn": "Shu-Yi Chen",
		"chairType": "Sponsor Chairs",
		"image": "/images/people/shu_yi_chen.jpg",
		"institution": "銘傳大學",
		"institutionEn": "Ming Chuan University",
		"department": "資訊管理系",
		"departmentEn": "Department of Information Management",
		"notes": "助理教授",
		"order": 0
	},
	{
		"id": "311ceff5-4470-817b-841f-ddc76d9c7e41",
		"name": "袁千雯",
		"nameEn": "Chien Wen Yuan",
		"chairType": "Family Chairs",
		"image": "/images/people/chien_wen_yuan.png",
		"institution": "國立臺灣大學",
		"institutionEn": "National Taiwan University",
		"department": "創新領域學士學位學程",
		"departmentEn": "Trans-disciplinary Bachelor Degree Program",
		"notes": "教授",
		"order": 0
	},
	{
		"id": "311ceff5-4470-81c4-84a2-f4a94b0d1341",
		"name": "畢南怡",
		"nameEn": "Nanyi Bi",
		"chairType": "Family Chairs",
		"image": "/images/people/nanyi_bi.png",
		"institution": "國立臺灣大學",
		"institutionEn": "National Taiwan University",
		"department": "資訊管理系",
		"departmentEn": "Department of Information Management",
		"notes": "助理教授",
		"order": 1
	},
	{
		"id": "311ceff5-4470-811a-8fcd-e302394efe28",
		"name": "黃書緯",
		"nameEn": "Shu-Wei Huang",
		"chairType": "Beer Chairs",
		"image": "/images/people/shu_wei_huang.jpg",
		"institution": "國立臺灣大學",
		"institutionEn": "National Taiwan University",
		"department": "創新領域學士學位學程",
		"departmentEn": "Trans-disciplinary Bachelor Degree Program",
		"notes": "助理教授",
		"order": 0
	},
	{
		"id": "311ceff5-4470-81c9-8c04-dd4774f56d6e",
		"name": "何樵暐",
		"nameEn": "Chiao-Wei Ho",
		"chairType": "Performance Chairs",
		"image": "/images/people/chiao_wei_ho.jpg",
		"institution": "Digital Medicine Lab",
		"institutionEn": "Digital Medicine Lab",
		"notes": "創辦人",
		"order": 0
	},
	{
		"id": "311ceff5-4470-81cb-88ad-f7d98b684651",
		"name": "林雨翾",
		"chairType": "Publicity Chairs",
		"image": "/images/people/_placeholder_person.jpg",
		"institution": "國立政治大學",
		"institutionEn": "National Chengchi University",
		"department": "政大數位內容與科技碩士學程",
		"departmentEn": "Graduate Program in Digital Content and Technologies",
		"notes": "碩士生",
		"order": 1
	},
	{
		"id": "311ceff5-4470-818c-ac4b-d1832d2c0972",
		"name": "侯宗佑",
		"nameEn": "Yoyo Tsung-Yu Hou",
		"chairType": "Publicity Chairs",
		"image": "/images/people/yoyo_tsung_yu_hou.jpg",
		"institution": "國立政治大學",
		"institutionEn": "National Chengchi University",
		"department": "數位內容碩士學位學程",
		"departmentEn": "Graduate Program in Digital Content and Technologies",
		"notes": "助理教授",
		"order": 0
	},
	{
		"id": "311ceff5-4470-8157-bc6c-c85f39fdf2fb",
		"name": "蔡岱臻",
		"nameEn": "Tai-Chen Tsai",
		"chairType": "Workshop Chairs",
		"image": "/images/people/_placeholder_person.jpg",
		"institution": "國立清華大學",
		"institutionEn": "National Tsing Hua University",
		"department": "資訊系統與應用研究所",
		"departmentEn": "Institute of Information Systems and Applications",
		"notes": "博士候選人",
		"order": 1
	},
	{
		"id": "311ceff5-4470-8193-b343-f3fcf3059e84",
		"name": "許峻誠",
		"nameEn": "Chun-Cheng Hsu",
		"chairType": "Workshop Chairs",
		"image": "/images/people/chun_cheng_hsu.jpg",
		"institution": "國立陽明交通大學",
		"institutionEn": "National Yang Ming Chiao Tung University",
		"department": "應用藝術研究所",
		"departmentEn": "Institute of Applied Arts",
		"notes": "教授",
		"order": 0
	},
	{
		"id": "311ceff5-4470-81a9-99cd-eff7d65fe9f4",
		"name": "張永儒",
		"nameEn": "Yung-Ju Chang",
		"chairType": "Panel Chairs",
		"image": "/images/people/yung_ju_chang.png",
		"institution": "國立陽明交通大學",
		"institutionEn": "National Yang Ming Chiao Tung University",
		"department": "資訊工程系",
		"departmentEn": "Department of Computer Science",
		"notes": "教授",
		"order": 0
	},
	{
		"id": "311ceff5-4470-814f-8384-c73e1e14c1d1",
		"name": "洪靖雯",
		"nameEn": "Ching-Wen Hung",
		"chairType": "Demo Chairs",
		"image": "/images/people/_placeholder_person.jpg",
		"institution": "國立臺灣大學",
		"institutionEn": "National Taiwan University",
		"department": "資訊網路與多媒體研究所",
		"departmentEn": "Graduate Institute of Networking and Multimedia",
		"notes": "博士候選人",
		"order": 0
	},
	{
		"id": "311ceff5-4470-81b5-aa4d-c6dad4e1ab34",
		"name": "莊偉銘",
		"nameEn": "Wei-Ming Chung",
		"chairType": "Poster Chairs",
		"image": "/images/people/_placeholder_person.jpg",
		"institution": "銘傳大學",
		"institutionEn": "Ming Chuan University",
		"department": "商品設計系",
		"departmentEn": "Department of Product Design",
		"notes": "講師",
		"order": 2
	},
	{
		"id": "311ceff5-4470-81ac-b962-f93b634f2d11",
		"name": "王秋玄",
		"nameEn": "Chiu-Hsuan Wang",
		"chairType": "Poster Chairs",
		"image": "/images/people/chiu_hsuan_wang.jpg",
		"institution": "國立臺灣大學",
		"institutionEn": "National Taiwan University",
		"department": "資訊管理系",
		"departmentEn": "Department of Information Management",
		"notes": "博士後研究員",
		"order": 1
	},
	{
		"id": "311ceff5-4470-8167-9143-e5764922c29a",
		"name": "程芙茵",
		"nameEn": "Fu-Yin Cherng",
		"chairType": "Poster Chairs",
		"image": "/images/people/fu_yin_cherng.png",
		"institution": "國立成功大學",
		"institutionEn": "National Cheng Kung University",
		"department": "資訊工程系",
		"departmentEn": "Department of Computer Science and Information Engineering",
		"notes": "助理教授",
		"order": 0
	},
	{
		"id": "311ceff5-4470-8112-abc9-eb64caeb2d42",
		"name": "蔡欣叡",
		"nameEn": "Hsin-Ruey Tsai",
		"chairType": "Paper Chairs",
		"image": "/images/people/hsin_ruey_tsai.jpg",
		"institution": "國立政治大學",
		"institutionEn": "National Chengchi University",
		"department": "資訊科學系",
		"departmentEn": "Department of Computer Science",
		"notes": "副教授",
		"order": 1
	},
	{
		"id": "311ceff5-4470-8198-b050-f1ba260d3d71",
		"name": "鄧善元",
		"nameEn": "Shan-Yuan Teng",
		"chairType": "Paper Chairs",
		"image": "/images/people/shan_yuan_teng.jpg",
		"institution": "國立臺灣大學",
		"institutionEn": "National Taiwan University",
		"department": "資訊工程系",
		"departmentEn": "Department of Computer Science and Information Engineering",
		"notes": "助理教授",
		"order": 3
	},
	{
		"id": "311ceff5-4470-81ea-a6d7-ffd10930330a",
		"name": "顏羽君",
		"nameEn": "Yu-Chun Yen",
		"chairType": "Paper Chairs",
		"image": "/images/people/yu_chun_yen.png",
		"institution": "國立陽明交通大學",
		"institutionEn": "National Yang Ming Chiao Tung University",
		"department": "資訊工程系",
		"departmentEn": "Department of Computer Science",
		"notes": "助理教授",
		"order": 2
	},
	{
		"id": "311ceff5-4470-81f8-bf3c-c408bcc7d8e7",
		"name": "莊雅量",
		"nameEn": "Yaliang Chuang",
		"chairType": "Paper Chairs",
		"image": "/images/people/yaliang_chuang.jpg",
		"institution": "國立清華大學",
		"institutionEn": "National Tsing Hua University",
		"department": "藝術設計系",
		"departmentEn": "Department of Arts and Design",
		"notes": "副教授",
		"order": 0
	},
	{
		"id": "311ceff5-4470-8142-8792-ec014e1a5e33",
		"name": "梁容輝",
		"nameEn": "Rung-Huei Liang",
		"chairType": "Steering Committees",
		"image": "/images/people/rung_huei_liang.png",
		"institution": "國立臺灣科技大學",
		"institutionEn": "National Taiwan University of Science and Technology",
		"department": "設計系",
		"departmentEn": "Department of Design",
		"notes": "副教授",
		"order": 2
	},
	{
		"id": "311ceff5-4470-814a-89e4-ecb2c4d9feda",
		"name": "余能豪",
		"nameEn": "Neng-Hao Yu",
		"chairType": "Steering Committees",
		"image": "/images/people/neng_hao_yu.jpg",
		"institution": "國立臺灣科技大學",
		"institutionEn": "National Taiwan University of Science and Technology",
		"department": "設計系",
		"departmentEn": "Department of Design",
		"notes": "副教授",
		"order": 1
	},
	{
		"id": "311ceff5-4470-8131-ae27-c0f2517a578c",
		"name": "詹力韋",
		"nameEn": "Liwei Chan",
		"chairType": "Steering Committees",
		"image": "/images/people/liwei_chan.png",
		"institution": "國立陽明交通大學",
		"institutionEn": "National Yang Ming Chiao Tung University",
		"department": "資訊工程系",
		"departmentEn": "Department of Computer Science",
		"notes": "教授",
		"order": 0
	},
	{
		"id": "311ceff5-4470-8117-8d4c-d17d7183827a",
		"name": "鄭龍磻",
		"nameEn": "Lung-Pan Cheng",
		"chairType": "General Chairs",
		"image": "/images/people/lung_pan_cheng.jpg",
		"institution": "國立臺灣大學",
		"institutionEn": "National Taiwan University",
		"department": "資訊工程系",
		"departmentEn": "Department of Computer Science and Information Engineering",
		"notes": "副教授",
		"order": 3
	},
	{
		"id": "311ceff5-4470-81d8-bdcf-cfc11bb7ca6a",
		"name": "韓秉軒",
		"nameEn": "Ping-Hsuan Han",
		"chairType": "General Chairs",
		"image": "/images/people/ping_hsuan_han.jpg",
		"institution": "國立臺北科技大學",
		"institutionEn": "National Taipei University of Technology",
		"department": "互動設計系",
		"departmentEn": "Department of Interaction Design",
		"notes": "副教授",
		"order": 2
	},
	{
		"id": "311ceff5-4470-8153-8188-c3831ff4d988",
		"name": "潘則佑",
		"nameEn": "Tse-Yu Pan",
		"chairType": "General Chairs",
		"image": "/images/people/tse_yu_pan.png",
		"institution": "國立臺灣科技大學",
		"institutionEn": "National Taiwan University of Science and Technology",
		"department": "人工智慧跨域科技研究所",
		"departmentEn": "Graduate Institute of A.I. Cross-disciplinary Technology",
		"notes": "助理教授",
		"order": 1
	},
	{
		"id": "311ceff5-4470-8113-b50d-f0fdbb7caedb",
		"name": "鄭宇婷",
		"nameEn": "Yu-Ting Cheng",
		"chairType": "General Chairs",
		"image": "/images/people/yu_ting_cheng.png",
		"institution": "國立臺灣科技大學",
		"institutionEn": "National Taiwan University of Science and Technology",
		"department": "設計系",
		"departmentEn": "Department of Design",
		"notes": "助理教授",
		"order": 0
	}
];

export const FROZEN_SESSIONS: SessionItem[] = [
	{
		"id": "2e7ceff5-4470-8072-b13f-deda208a9293",
		"title": "Session",
		"day": "Day 1",
		"startTime": "",
		"endTime": ""
	},
	{
		"id": "2e7ceff5-4470-80e1-a75c-c34096504f16",
		"title": "Coffee Break",
		"day": "Day 1",
		"startTime": "10:30",
		"endTime": "10:50"
	},
	{
		"id": "2e7ceff5-4470-8077-bed1-cc15211f03e6",
		"title": "Lunch Break",
		"day": "Day 1",
		"startTime": "11:38",
		"endTime": "13:20"
	},
	{
		"id": "b2c271b8-26f6-4329-9f73-7532711e983f",
		"title": "Opening",
		"day": "Day 1",
		"startTime": "9:00",
		"endTime": "9:30"
	},
	{
		"id": "2e7ceff5-4470-807a-9349-de52b6648ce1",
		"title": "Opening Keynote: Writing Now! Keeping the Human Voice in AI-Assisted Writing",
		"day": "Day 1",
		"startTime": "9:30",
		"endTime": "10:30"
	},
	{
		"id": "2e7ceff5-4470-8077-8f04-de474842ed8d",
		"title": "Paper Session 3: 創新技術與智慧系統 / Emerging Technologies and Intelligent Systems",
		"day": "Day 2",
		"startTime": "9:00",
		"endTime": "10:00",
		"topics": [
			{
				"id": "2e7ceff5-4470-802e-ab4a-e15b8acefb0e",
				"topic": "From Message Assistants to Relational Mediators: Rethinking AI's Role in Shaping Early Disclosure in Online Dating",
				"startTime": "9:00",
				"endTime": "9:12",
				"sessionId": "2e7ceff5-4470-8077-8f04-de474842ed8d"
			},
			{
				"id": "2e7ceff5-4470-8042-a743-c29a6827393f",
				"topic": "FlueBricks: A Modular Toolkit for Interactive Flute-like Instrument Systems",
				"startTime": "9:12",
				"endTime": "9:24",
				"sessionId": "2e7ceff5-4470-8077-8f04-de474842ed8d"
			}
		]
	}
];

// 注意：站上公告實際使用 src/announcementsData.ts（含 modal / linkLabel 等 Notion 沒有的欄位），
// FROZEN_NEWS 僅為 Notion News 資料庫的凍結快照，目前無程式引用。
export const FROZEN_NEWS: NewsItem[] = [
	{
		"id": "382ceff5-4470-8156-868c-cad043542385",
		"title": "學生志工 (Student Volunteer) 招募中",
		"subtitle": "SV 招募",
		"content": "TAICHI 2026 學生志工（Student Volunteer, SV）開始招募！誠摯邀請對人機互動有興趣的同學加入，協助會議現場運作，並有機會近距離參與議程、認識研究社群。名額有限，歡迎填寫報名表單參加：https://forms.gle/2WNEyuApxP8yRgLV9",
		"date": "2026-06-17",
		"createdTime": "",
		"place": "",
		"image": "/images/news/_placeholder_news.jpg",
		"link": "https://forms.gle/2WNEyuApxP8yRgLV9"
	},
	{
		"id": "382ceff5-4470-813f-a938-e1dc7fa3927a",
		"title": "Call for Papers 投稿延期至 6/23",
		"subtitle": "投稿截止日期延長",
		"content": "TAICHI 2026 投稿截止日期延長！論文與圖像式論文（Paper & Pictorial）、海報論文（Poster）、互動展示（Demo）三類投稿截止日期，統一由原訂 2026/6/18（四）延長至 2026/6/23（二）23:59 (GMT+8)。審查結果通知（7/21）與最終完稿（7/27）日期維持不變。歡迎把握最後機會投稿！",
		"date": "2026-06-17",
		"createdTime": "",
		"place": "",
		"image": "/images/news/_placeholder_news.jpg",
		"link": "https://easychair.org/conferences/?conf=taichi2026"
	}
];
