// Offline-friendly fallback data.
// These entries are used only when Notion is unavailable or the proxy is not configured.

export const OFFLINE_PEOPLE: PersonItem[] = [
	{
		id: 'offline-general-1',
		name: 'Lin Mei-Hua / 林美樺',
		chairType: 'General Chairs',
		email: 'taiwanchi26@gmail.com',
		image: '/og-preview.png',
		institution: 'National Taipei University of Technology',
		department: 'Interaction Design',
		order: 1,
	},
	{
		id: 'offline-general-2',
		name: 'Hsu Chia-Jung / 許家榮',
		chairType: 'General Chairs',
		email: 'taiwanchi26@gmail.com',
		image: '/images/home_bg2.png',
		institution: 'National Taiwan University of Science and Technology',
		department: 'Design',
		order: 2,
	},
	{
		id: 'offline-general-3',
		name: 'Chou Yu-Han / 周郁涵',
		chairType: 'General Chairs',
		email: 'taiwanchi26@gmail.com',
		image: '/images/cfp_bg.avif',
		institution: 'National Cheng Kung University',
		department: 'Industrial Design',
		order: 3,
	},
	{
		id: 'offline-general-4',
		name: 'Hsiao Cheng-En / 蕭承恩',
		chairType: 'General Chairs',
		email: 'taiwanchi26@gmail.com',
		image: '/og-preview.png',
		institution: 'National Taiwan University',
		department: 'Computer Science',
		order: 4,
	},
	{
		id: 'offline-steering-1',
		name: 'Tsai Wen-Ling / 蔡文玲',
		chairType: 'Steering Committees',
		image: '/images/home_bg.png',
		institution: 'National Taiwan University',
		department: 'Design Research Center',
		order: 1,
	},
	{
		id: 'offline-steering-2',
		name: 'Kuo Chia-Hao / 郭家豪',
		chairType: 'Steering Committees',
		image: '/images/home_bg2.png',
		institution: 'National Taipei University of Technology',
		department: 'Interaction Design',
		order: 2,
	},
	{
		id: 'offline-steering-3',
		name: 'Liang Shu-Min / 梁淑敏',
		chairType: 'Steering Committees',
		image: '/images/cfp_bg.avif',
		institution: 'National Chengchi University',
		department: 'Digital Content',
		order: 3,
	},
	{
		id: 'offline-program-1',
		name: 'Liao Pei-Hsuan / 廖珮瑄',
		chairType: 'Program Chairs',
		image: '/images/home_bg.png',
		institution: 'National Yang Ming Chiao Tung University',
		department: 'Computer Science',
		order: 1,
	},
	{
		id: 'offline-program-2',
		name: 'Kuo Chih-Han / 郭志瀚',
		chairType: 'Program Chairs',
		image: '/images/cfp_bg.avif',
		institution: 'National Taipei University of Technology',
		department: 'Interaction Design',
		order: 2,
	},
	{
		id: 'offline-program-3',
		name: 'Wu Yi-Ting / 吳怡婷',
		chairType: 'Program Chairs',
		image: '/og-preview.png',
		institution: 'National Chengchi University',
		department: 'Digital Content',
		order: 3,
	},
	{
		id: 'offline-paper-1',
		name: 'Cheng Yu-Lin / 鄭宇霖',
		chairType: 'Paper Chairs',
		email: 'taiwanchi26+paper@gmail.com',
		image: '/images/home_bg2.png',
		institution: 'National Taiwan University',
		department: 'Computer Science and Information Engineering',
		order: 1,
	},
	{
		id: 'offline-paper-2',
		name: 'Tseng Shu-Fen / 曾淑芬',
		chairType: 'Paper Chairs',
		email: 'taiwanchi26+paper@gmail.com',
		image: '/images/home_bg.png',
		institution: 'National Taiwan Normal University',
		department: 'Technology Application and Human Resource Development',
		order: 2,
	},
	{
		id: 'offline-paper-3',
		name: 'Lo Chia-Lin / 羅嘉琳',
		chairType: 'Paper Chairs',
		email: 'taiwanchi26+paper@gmail.com',
		image: '/images/cfp_bg.avif',
		institution: 'National Sun Yat-sen University',
		department: 'Human-Centered Computing',
		order: 3,
	},
	{
		id: 'offline-paper-4',
		name: 'Peng Ting-Yu / 彭庭妤',
		chairType: 'Paper Chairs',
		email: 'taiwanchi26+paper@gmail.com',
		image: '/og-preview.png',
		institution: 'National Central University',
		department: 'Learning and Instruction',
		order: 4,
	},
	{
		id: 'offline-poster-1',
		name: 'Wang Yi-Chen / 王怡禎',
		chairType: 'Poster Chairs',
		email: 'taiwanchi26+poster@gmail.com',
		image: '/images/cfp_bg.avif',
		institution: 'National Cheng Kung University',
		department: 'Industrial Design',
		order: 1,
	},
	{
		id: 'offline-poster-2',
		name: 'Chen Tzu-Ling / 陳姿伶',
		chairType: 'Poster Chairs',
		email: 'taiwanchi26+poster@gmail.com',
		image: '/images/home_bg2.png',
		institution: 'National Taipei University of Education',
		department: 'Digital Technology Design',
		order: 2,
	},
	{
		id: 'offline-poster-3',
		name: 'Huang Hsin-Yi / 黃欣怡',
		chairType: 'Poster Chairs',
		email: 'taiwanchi26+poster@gmail.com',
		image: '/og-preview.png',
		institution: 'National Tsing Hua University',
		department: 'Service Science',
		order: 3,
	},
	{
		id: 'offline-demo-1',
		name: 'Tsai Po-Han / 蔡柏翰',
		chairType: 'Demo Chairs',
		email: 'taiwanchi26+demo@gmail.com',
		image: '/images/home_bg.png',
		institution: 'National Yang Ming Chiao Tung University',
		department: 'Institute of Computer Science',
		order: 1,
	},
	{
		id: 'offline-workshop-1',
		name: 'Peng Hsin-Yu / 彭馨瑜',
		chairType: 'Workshop Chairs',
		image: '/images/home_bg.png',
		institution: 'National Taiwan University',
		department: 'Design Research Center',
		order: 1,
	},
	{
		id: 'offline-workshop-2',
		name: 'Teng Chia-Yi / 鄧佳宜',
		chairType: 'Workshop Chairs',
		image: '/images/home_bg2.png',
		institution: 'National Kaohsiung University of Science and Technology',
		department: 'Creative Design',
		order: 2,
	},
	{
		id: 'offline-publicity-1',
		name: 'Yeh Chih-Hao / 葉志豪',
		chairType: 'Publicity Chairs',
		image: '/images/home_bg2.png',
		institution: 'National Taipei University of Technology',
		department: 'Communication Design',
		order: 1,
	},
	{
		id: 'offline-publicity-2',
		name: 'Su Pei-Ju / 蘇珮如',
		chairType: 'Publicity Chairs',
		image: '/images/cfp_bg.avif',
		institution: 'National Taiwan University of Arts',
		department: 'Visual Communication',
		order: 2,
	},
	{
		id: 'offline-panel-1',
		name: 'Chen Po-Jen / 陳柏任',
		chairType: 'Panel Chairs',
		image: '/og-preview.png',
		institution: 'National Cheng Kung University',
		department: 'Human Factors',
		order: 1,
	},
	{
		id: 'offline-performance-1',
		name: 'Shen Yu-Ting / 沈語庭',
		chairType: 'Performance Chairs',
		image: '/images/home_bg.png',
		institution: 'Taipei National University of the Arts',
		department: 'New Media Art',
		order: 1,
	},
	{
		id: 'offline-beer-1',
		name: 'Lin Chao-Wei / 林昭維',
		chairType: 'Beer Chairs',
		image: '/images/home_bg2.png',
		institution: 'National Taiwan University',
		department: 'Community Engagement',
		order: 1,
	},
	{
		id: 'offline-family-1',
		name: 'Yen Hsiao-Ching / 顏筱晴',
		chairType: 'Family Chairs',
		image: '/images/cfp_bg.avif',
		institution: 'National Chengchi University',
		department: 'Educational Technology',
		order: 1,
	},
	{
		id: 'offline-family-2',
		name: 'Kao Wen-Chi / 高文綺',
		chairType: 'Family Chairs',
		image: '/images/home_bg.png',
		institution: 'National Taiwan University of Science and Technology',
		department: 'Design',
		order: 2,
	},
	{
		id: 'offline-family-3',
		name: 'Lee Min-Hui / 李敏慧',
		chairType: 'Family Chairs',
		image: '/og-preview.png',
		institution: 'National Taipei University of Education',
		department: 'Children and Family Studies',
		order: 3,
	},
	{
		id: 'offline-sponsor-1',
		name: 'Ou Kai-Hung / 歐凱宏',
		chairType: 'Sponsor Chairs',
		image: '/images/home_bg2.png',
		institution: 'National Taiwan University',
		department: 'Industry Liaison',
		order: 1,
	},
	{
		id: 'offline-web-1',
		name: 'Lin Po-Yu / 林柏宇',
		chairType: 'Web Chairs',
		image: '/og-preview.png',
		institution: 'National Taiwan University of Science and Technology',
		department: 'Information Management',
		order: 1,
	},
	{
		id: 'offline-visual-1',
		name: 'Cheng Chia-Yun / 鄭佳芸',
		chairType: 'Visual Chairs',
		image: '/images/home_bg.png',
		institution: 'National Taipei University of Technology',
		department: 'Visual Design',
		order: 1,
	},
	{
		id: 'offline-visual-2',
		name: 'Wu Shao-Min / 吳紹敏',
		chairType: 'Visual Chairs',
		image: '/images/cfp_bg.avif',
		institution: 'National Taiwan University of Arts',
		department: 'Communication Design',
		order: 2,
	},
	{
		id: 'offline-registration-1',
		name: 'Liu Hsin-Ting / 劉欣庭',
		chairType: 'Registration Chairs',
		image: '/og-preview.png',
		institution: 'National Cheng Kung University',
		department: 'Conference Operations',
		order: 1,
	},
	{
		id: 'offline-student-volunteer-1',
		name: 'Huang Po-Han / 黃柏翰',
		chairType: 'Student Volunteer Chairs',
		image: '/images/home_bg2.png',
		institution: 'National Taiwan University',
		department: 'Computer Science',
		order: 1,
	},
	{
		id: 'offline-student-volunteer-2',
		name: 'Tseng Yu-An / 曾郁安',
		chairType: 'Student Volunteer Chairs',
		image: '/images/home_bg.png',
		institution: 'National Taipei University of Technology',
		department: 'Interaction Design',
		order: 2,
	},
	{
		id: 'offline-keynote-1',
		name: 'Prof. Aya Nakamura',
		chairType: 'Keynote Speaker / Designing Futures with Playful Systems',
		image: '/images/home_bg2.png',
		institution: 'Future Interfaces Lab',
		department: 'Keynote Speaker',
		order: 1,
	},
	{
		id: 'offline-keynote-2',
		name: 'Dr. Chen Wei-Ting',
		chairType: 'Keynote Speaker / Human-AI Collaboration in Public Space',
		image: '/images/cfp_bg.avif',
		institution: 'Urban Experience Studio',
		department: 'Keynote Speaker',
		order: 2,
	},
];

export const OFFLINE_SESSIONS: SessionItem[] = [
	{
		id: 'offline-session-1',
		title: 'Opening, Welcome, and Community Updates',
		day: 'Day 1',
		startTime: '09:00',
		endTime: '10:00',
		chairs: [OFFLINE_PEOPLE[0]],
		topics: [
			{
				id: 'offline-topic-1',
				topic: 'TAICHI 2026 Theme Introduction',
				startTime: '09:00',
				endTime: '09:20',
				chairs: [OFFLINE_PEOPLE[0]],
			},
			{
				id: 'offline-topic-2',
				topic: 'Call for Papers and Community Participation',
				startTime: '09:20',
				endTime: '10:00',
				chairs: [OFFLINE_PEOPLE[1], OFFLINE_PEOPLE[2]],
			},
		],
	},
	{
		id: 'offline-session-2',
		title: 'Paper and Pictorial Presentations',
		day: 'Day 1',
		startTime: '13:30',
		endTime: '15:00',
		chairs: [OFFLINE_PEOPLE[1]],
		topics: [
			{
				id: 'offline-topic-3',
				topic: 'Making Research Tangible Through Pictorial Storytelling',
				startTime: '13:30',
				endTime: '14:10',
				chairs: [OFFLINE_PEOPLE[1]],
			},
			{
				id: 'offline-topic-4',
				topic: 'Material Prototypes for Embodied Interaction',
				startTime: '14:10',
				endTime: '15:00',
				chairs: [OFFLINE_PEOPLE[1]],
			},
		],
	},
	{
		id: 'offline-session-3',
		title: 'Poster and Demo Showcase',
		day: 'Day 2',
		startTime: '10:30',
		endTime: '12:00',
		chairs: [OFFLINE_PEOPLE[2], OFFLINE_PEOPLE[3]],
		topics: [
			{
				id: 'offline-topic-5',
				topic: 'Interactive Poster Session',
				startTime: '10:30',
				endTime: '11:10',
				chairs: [OFFLINE_PEOPLE[2]],
			},
			{
				id: 'offline-topic-6',
				topic: 'Live Demo Walkthroughs',
				startTime: '11:10',
				endTime: '12:00',
				chairs: [OFFLINE_PEOPLE[3]],
			},
		],
	},
];

export const OFFLINE_NEWS: NewsItem[] = [
	{
		id: 'offline-news-sv-results',
		title: '學生志工錄取名單出爐',
		subtitle: 'Student Volunteer 錄取公告',
		content:
			'經過團隊審慎評選，第 12 屆台灣人機互動研討會的「學生志工」錄取名單正式出爐 💥☄️⚡\n\n📬 錄取者注意事項：\n- 錄取結果與後續詳細事項，將於今日後陸續寄送至各位報名時填寫的電子信箱。請務必前往收件匣（包含垃圾郵件匣）確認，並依照信中說明完成相關手續 🤜 🤛\n- 請錄取夥伴預留 8/4-8/6 的時間，參與行前說明、場地佈置以及研討會當日的支援工作 🤟\n\n📧 若有任何問題，歡迎來信詢問：taiwanchi26+sv@gmail.com',
		date: '2026/07/12',
		createdTime: '2026/07/12',
		place: 'Online',
		image: '/images/home_bg.png',
		link: '',
		linkLabel: '查看錄取名單',
		modal: {
			title: '學生志工錄取名單',
			// 半匿名：中間字以 ○ 遮罩
			names: [
				'賴○綸', '林○臻', '游○儀', '黃○淇', '林○嬡',
				'李○璋', '李○萱', '魏○儀', '徐○維', '蔡○庠',
				'曾○呈', '蔡○鈞', '蔡○宏', '陳○蓉', '盧○儒',
				'黃○文', '林○均', '林○辰', '陳○潼', '張○婷',
			],
			note: '名單以半匿名方式顯示，完整錄取資訊以通知信為準；有疑問請來信 taiwanchi26+sv@gmail.com。',
		},
	},
	{
		id: 'offline-news-cfp-extend',
		title: 'Call for Papers 投稿延期至 6/23',
		subtitle: '投稿截止日期延長',
		content:
			'TAICHI 2026 投稿截止日期延長！\n\n論文與圖像式論文（Paper & Pictorial）、海報論文（Poster）、互動展示（Demo）三類投稿截止日期，統一由原訂 2026/6/18（四）延長至 2026/6/23（二）23:59 (GMT+8)。\n\n歡迎把握最後機會投稿！',
		date: '2026/06/17',
		createdTime: '2026/06/17',
		place: 'Online',
		image: '/images/cfp_bg.avif',
		link: 'https://easychair.org/conferences/?conf=taichi2026',
		linkLabel: '前往投稿系統',
	},
	{
		id: 'offline-news-sv',
		title: '學生志工 (Student Volunteer) 招募中',
		subtitle: 'Student Volunteer 招募公告',
		content:
			'TAICHI 2026 學生志工（Student Volunteer, SV）開始招募！\n\n誠摯邀請對人機互動有興趣的同學加入，協助會議現場運作，並有機會近距離參與議程、認識研究社群。\n\n歡迎點擊下方按鈕填寫報名表單。',
		date: '2026/06/17',
		createdTime: '2026/06/17',
		place: 'Online',
		image: '/images/home_bg.png',
		link: 'https://forms.gle/2WNEyuApxP8yRgLV9',
		linkLabel: '前往報名表單',
		closedLabel: '報名已截止',
	},
];
